### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/resourcedata.org#10]
As logins are going back and forth, perhaps the site should be deployed to https://?

@NRGI/vitamin some tips if you are using nginx here:
https://github.com/ckan/ckan/wiki/SSL#nginx-configuration

**Comment by anderspeders** [comment]
Have reached out in email to our sysadmin.

**Comment by iprunache** [comment]
@mattfullerton thanks for the tip! We're using AWS ELB for SSL which directs both HTTP and HTTPS traffic to port 80 of the container. They're setting `X-Forwarded-Proto` so we should be fine.

I've tried setting the correct protocol for the site url on the production site but it doesn't seem to work, site links still point to `http`. It worked on staging though when I updated the `SITE_SCHEME` variable to `https` so we'll have to wait to get that on production too.

**Comment by iprunache** [comment]
I think we still need to redirect from `http://www.resourcedata.org` to `https://www.resourcedat.org` to force everyone to use the secure site.

**Comment by iprunache** [comment]
I'll leave this open until we verify that it works in production and that all site links point to the `https` version too.

**Comment by iprunache** [comment]
Verified that this works for https://www.resourcedata.org.

There are still some cleanup left to do to make full advantage of https, see issues #81 and #82.
