### ISSUE TITLE
Support multiple country and year and "used for scoring" values (was: No structured keys when adding new dataset)

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#101]
What happened to the structured metadata fields when inputting new dataset? They seem to have been replaced by this "Custom field", define-your-own structure. My concern is how this will affect faceted searching.

This happens on the staging server.

![image](https://user-images.githubusercontent.com/19787025/27197430-2a19f406-51dc-11e7-8bef-112ddba22f9f.png)

**Comment by mattfullerton** [comment]
This has changed because I set the schema to apply to documents and not datasets (i.e. only RGI). Are there elements of the RGI form that you need for custom-input NRGI datasets? I can create a second schema for datasets.

Anyway, in case you want to create _documents_, you can go to http://li1665-139.members.linode.com/document/new

**Comment by moman822** [comment]
For datasets, I would like roughly the same schema as is on ResourceData currently for datasets.

So, as below minus "Assesment type" & "Question"

If possible (and not too much work at this point), Country and Year should be able to take multiple values.

The rest can remain.


![image](https://user-images.githubusercontent.com/19787025/27226656-0f420b4a-526e-11e7-94a3-b16850beb243.png)

**Comment by mattfullerton** [comment]
Country and Year multiple values will have to wait until multiple values generally are working better.

A second schema for datasets will have to wait a few days...

**Comment by mattfullerton** [comment]
"Fixed" - https://staging.resourcedata.org/dataset/new

Leaving open and renaming re. multiple values for years and countries
