### ISSUE TITLE
Link from dataset metadata

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#102]
What are the rules governing when these fields are links and when they are not?

See: https://www.resourcedata.org/dataset/peru-extractive-industry-contextual-data1

![image](https://user-images.githubusercontent.com/19787025/27197887-0ae527fc-51de-11e7-8909-2aa87b8bc046.png)

**Comment by mattfullerton** [comment]
Assessment Type, Questions, Year, Category (shouldn't we rename this sub-component?), Country, Country-ISO get links.

Law/Practice will also be linked, Scoring tag probably (depends a little on how that finally is displayed, whether a search for other datasets with a similar status makes sense.

**Comment by anderspeders** [comment]
Note that this issue is *not* related to the RGI source library

**Comment by mattfullerton** [comment]
@anderspeders It is - these links appear on RGI document pages

**Comment by mattfullerton** [comment]
Short term fix: link to search of current document type

Near term: See #120

**Comment by mattfullerton** [comment]
Short term fix is done, closing in favour of #120
