### ISSUE TITLE
Add `version.txt` page to root of the site

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#104]
## Why
Add a `version.txt` page that contains the Docker image name from which the site currently runs so that we can quickly say which version of the site is deployed.

## What
- [x] a `version.txt` page is added to the site root at Docker build time
   - [x] the page contains then name of the image being built, including the SHA of the latest Github commit being included in the image

**Comment by adinuca** [comment]
This has been done in https://github.com/derilinx/ckan-docker-public#boards?repos=90724568 .
