### ISSUE TITLE
Schedule RGI import to run daily

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#105]
## Why
To make sure that the site has the latest resources from RGI.

## What
- [ ] an AWS lambda function is scheduled to run the RGI import script daily from AWS ECS

**Comment by anderspeders** [comment]
The RGI is fixed / static data so this should not be needed as long as we get to the approx. 9700 documents. 

Thus suggesting that we close this - if I understood it correctly.

**Comment by iprunache** [comment]
OK, will run it manually in case there are updates to the code until we get all the documents available.
