### ISSUE TITLE
Analysis section not showing on staging

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#107]
The various pages I created under the CKAN "Pages" functionality on the linode server are not available on the staging server.

See: http://li1665-139.members.linode.com/pages

vs.

https://staging.resourcedata.org/pages

**Comment by mattfullerton** [comment]
As these are content changes and not code changes, you will have to copy them over manually. I don't have a good solution to this as the pages extension doesn't have an API.
