### ISSUE TITLE
Clicking "Documents" tab issues

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#109]
When clicking the "Documents" tab, a few issues are revealed:

The "Datasets" tab button is show as active instead of "Documents"

The tab header shows "Datasets"

Document count shown as "9000 datasets found"

See: https://staging.resourcedata.org/document

![image](https://user-images.githubusercontent.com/19787025/27434455-bf90337a-5726-11e7-8b48-229b2bcc12e4.png)

**Comment by mattfullerton** [comment]
1. N.B. This might be solved pre-launch by just dehighlighting all tabs
2&3 - this should be a quick fix

**Comment by mattfullerton** [comment]
Closing in favour of #110 (Item 1). 2&3 are done in 54a2be32aed47b7fd1665c3b04f1d52c84e099a6 and (3) also submitted to CKAN as a pull request (https://github.com/ckan/ckan/pull/3643)
