### ISSUE TITLE
Tab button highlighting (was: "Analysis" tab button highlight)

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#110]
The "Analysis" tab button does not highlight when clicked.

Datasets highlighted when Documents should be.

Currently, all highlighting is turned off

**Comment by mattfullerton** [comment]
N.B. This might be solved pre-launch by just dehighlighting all tabs

**Comment by mattfullerton** [comment]
Update/Note-to-self: CKAN seems to be lacking the functionality to highlight the link when the link is not coming from a controller (our extension is also detecting these "simple" links and intervening. Not yet sure whether to intervene in extension or in CKAN core.

**Comment by mattfullerton** [comment]
The commit reference above was a mistake in the commit message
