### ISSUE TITLE
Front page info box changes

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#113]
Final input on changes to info boxes on front pages

![image](https://user-images.githubusercontent.com/19787025/27442499-61186b74-573e-11e7-8c13-1866e8537b2a.png)

**Comment by moman822** [comment]
@anderspeders can you outline the changes you wanted?

**Comment by mattfullerton** [comment]
Suggestion (from me and from what I remember from Anders in the call):
- swap 1&3
- 1 becomes focused on analysis with slightly different text and links to same destination as "Analysis" tab
- 2 highlights the EITI data with link to EITI organization. We can supply another image for that in similar style to the others if required (updates disappears as covered by subscribe in footer)

**Comment by moman822** [comment]
can we return the category icon links and the country links inbetween the banner and the info boxes? these were cut out it appears.

@mattfullerton

**Comment by moman822** [comment]
These have disappeared:

![image](https://user-images.githubusercontent.com/19787025/27554962-32337dec-5a7e-11e7-9eb5-e7008b67fc60.png)

**Comment by mattfullerton** [comment]
I would have left these out until #119 and #120 are done, otherwise they are not linking to much. Its a 2 minute change to put them back.

**Comment by moman822** [comment]
I will discuss w/ Anders.

In the meantime, Dem. Rep. Congo is not correctly linked. 

Currently directs to: `?country=Dem.%20Rep.%20of%20Congo`

Should point to `?country=Congo%2C+the+Democratic+Republic+of+the`

**Comment by anderspeders** [comment]
Please move Box 3 to the location of Box 1

**Comment by anderspeders** [comment]
Can we get the analysis box live as well.

**Comment by mattfullerton** [comment]
This is all already done on staging - can you please look there and say if its OK

@anderspeders

**Comment by moman822** [comment]
It  looks good. Is the new EITI box going to be implemented soon as well?

**Comment by mattfullerton** [comment]
EITI box is up and DRC link changed (sorry, that last one had gotten overlooked).
