### ISSUE TITLE
Cote d'Ivoire resources have invalid URLs after import

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#117]
## Why
The EITI harvester should create valid URLs for all the resources uploaded to CKAN so they can be properly visualized and accessed.

Right now the Cote d'Ivoire resources have invalid URLs pointing to local paths on the havester.

## What
- [ ] Cote d'Ivoire resources have URLs that point to the resourcedata.org site instead of a local harvester path.

## Notes
https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-cote-d-ivoire/resource/ddd660c6-5bdc-433b-a818-caef82d6a36f

Notice the URL: `http://./out/company/cote-d-ivoire-company.csv`

**Comment by mattfullerton** [comment]
Fixed in https://github.com/NRGI/resourcedata.org/commit/81c194d2fefdb786e1464167c2dbbf56be04b883
