### ISSUE TITLE
Remaining design/UI issues

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#118]
To do:

~~#31 Email subscribe field~~
~~#84 double scrollers on dataset previews~~
~~#89 change "Got to resource" button to "Download"~~
~~#109 Documents tab issues (new)~~
~~#110 Analysis tab issue (new)~~
~~#112 change Organization tile look~~
~~#113 front page info box changes~~
~~#114 link doc/dataset tabs from front page~~

**Comment by mattfullerton** [comment]
All done...
