### ISSUE TITLE
Categories on front page

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/resourcedata.org#119]
~~~Short term (suggestion - @anderspeders , @moman822 - please let me know): hide them~~~

~~~Near term:~~~ Use categories as an _additional_ field to sub-component (RGI only) and have a mapping between RGI questions and categories.

Related to #120

**Comment by mattfullerton** [comment]
@anderspeders @moman822 I am still lacking the mapping

**Comment by mattfullerton** [comment]
Moving to next milestone

**Comment by mattfullerton** [comment]
The new field bit is done

**Comment by mattfullerton** [comment]
Moving to next milestone as we still don't have the mapping

**Comment by moman822** [comment]
@mattfullerton an update on this:

We will have a mapping of question numbers to categories (aka 'precepts' aka front page tiles) soon. With that, you will be able to tag each document based on question number. Thanks to your great work so far, a couple things are possible (please correct if wrong):

* One document can have multiple category tags. E.g. Question 1.1a is mapped to "Taxation" and "Local Effects", all documents for 1.1a will have two "Category" tags. If a document has two question tags, it won't be a problem.
* Both Datasets & Documents can be shown on the same facet page when clicking on the tile, if they are tagged to the same "Category". Following this structure: https://www.resourcedata.org/dataset?_show_all_types=True&year=2016

What is the best format to provide the mapping? 

* CSV, one column for questions, multiple columns for categories
* CSV, one column for questions, one column with categories
* Some kind of nested JSON structure

**Comment by mattfullerton** [comment]
@moman822 

- Only minor correction is that I wasn't expecting multiple values of category per dataset/document, but now that we have the basics nailed down its not a lot of work to add that (we'll need to reindex, again, as this is a change to the Solr search schema)

Best format: CSV, multiple columns for categories. Feel free to reuse the last questions sheet you sent. But a sep. file is fine too.

**Comment by moman822** [comment]
@mattfullerton sending the file on slack.

**Comment by mattfullerton** [comment]
Many thanks

**Comment by moman822** [comment]
@mattfullerton Updated file w/ slightly new Precept names is on slack.

**Comment by mattfullerton** [comment]
I think this is finally completely done and viewable on dev: http://li1665-139.members.linode.com/. Will coordinate the push to staging and production with @iprunache
