### ISSUE TITLE
EITI Complete summary dataset, no description

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#123]
Can we implement the same standard text as for all other EITI files here as well? I will implement via CMS but I am not sure if this needs to be done elsewhere for when the site updates. If that is enough, please close.

<a href="google.com" target="_blank">TEXT</a>

See: https://staging.resourcedata.org/dataset/eiti-complete-summary-table

**Comment by mattfullerton** [comment]
Thanks for doing it manually, update fix is done in importer now
