### ISSUE TITLE
Add Excel previewer for Excel files

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#125]
this was implemented succesfully in staging.resourcedata.org (https://staging.resourcedata.org/dataset/latin-america-extractive-industry-contextual-data/resource/113ea5f8-6881-41eb-9968-624d08b31958) but not carried over to production.

**Comment by mattfullerton** [comment]
@moman822 Again, it's a content thing, I believe the preview was added manually on staging and hence would need added manually on production. I'll see if I can set it up that it's auto-added for Excel and will turn off the attempt to add Excel files to the datastore automatically. Should be possible (we actually want to prevent the data explorer preview coming up for Excel files, and have this instead).

**Comment by mattfullerton** [comment]
Fixed in https://github.com/derilinx/ckan-docker-public/commit/1b98cff77599c673cf7e260417284aecb484957c
