### ISSUE TITLE
New navigation path from Organization tab

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#126]
If a user clicks on the organization tab, they will be shown the tiles for the various organizations with the nice images. Clicking on those will take them directly to the data. I think it would be better to go from the tiles to the About page for the org. (e.g. https://www.resourcedata.org/organization/about/eiti) and then have an obivous redirection from there to the data. This makes more sense as the current structure does not give much obvious info about what the org. actually is, other than the nice logo.

Not urgent, can be on the July timeframe.

**Comment by mattfullerton** [comment]
We've had a think about this and would really advise against it. Its definitely doable and probably not much work, but you're going against the grain of the "normal" CKAN user experience. The information on the organization is available in the left-hand sidebar.

**Comment by mattfullerton** [comment]
@moman822 @anderspeders need feedback here

**Comment by moman822** [comment]
We can go with your rec.
