### ISSUE TITLE
[EITI-harvester] Add time stamps to EITI sheet

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#127]
## Why

EITI has now added a time stamp for (as I recall): 
- date added
- date moderated

Please add these to the EITI Summary data tables and include these in all 50 country tables include the complete summary data file. 

Tommy will be in touch on further details.

**Comment by anderspeders** [comment]
Could this be added to one of the upcoming sprints @mattfullerton ?

**Comment by anderspeders** [comment]
@mattfullerton @moman822 Just following up if there are any updates here?

**Comment by mattfullerton** [comment]
@anderspeders Was about to ask @moman822 for more details - haven't heard anything yet.

In the summary API endpoint, I'm seeing a "status_date" under country, nothing under reports.

Under revenue, I get "created" and "changed" under organisation, but it was null in the spot test I did. I would run a test to see if its ever not null and what format the date is in. I assume these are the ones we're interested in?

e.g. https://eiti.org/api/v1.0/revenue/121365

Under the organisation endpoint I get no dates.

**Comment by moman822** [comment]
@mattfullerton yes, that is what we are interested in. Can you check if these exist for any records?

One thing we are after here is some way to notify when new data is available- does using this variable seem like a good starting point for that or do you have another idea?

**Comment by mattfullerton** [comment]
@moman822 I checked yesterday, there is not data in any of them.

Without understanding what this variable is for (why is it nested under Organisation?) I can't make any comment on whether it's what you want or what it can be used for..., sorry

**Comment by anderspeders** [comment]
@moman822 As discussed please follow up with a review of the API and let's then follow up with EITI.

**Comment by moman822** [comment]
@mattfullerton the relevant timestamps are in the `summary_data` endpoint here: https://eiti.org/api/v1.0/summary_data as `created` and `changed`

Is it possible to incorporate these into the ResourceData data?

**Comment by anderspeders** [comment]
So these should be added as additional columns for dataset both for entity and company file formats using ISO standard.

**Comment by mattfullerton** [comment]
This is done now in the import, not sure how I missed seeing those fields. As we now have change detection on resource upload (#88), followed datasets should send an email alert if these dates change. Is that enough?

**Comment by mattfullerton** [comment]
e.g. http://li1665-139.members.linode.com/dataset/eiti-summary-data-table-for-albania/resource/2e9bb037-a02a-4cdb-baa4-f6e06fd033ea

**Comment by moman822** [comment]
@mattfullerton that link does not work

**Comment by moman822** [comment]
Is there a way we can have a more general alert for all EITI data that someone could subscribe to (instead of  'following' every single dataset)?

**Comment by mattfullerton** [comment]
Good idea @anderspeders
