### ISSUE TITLE
Add second search bar to main page

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#129]
The search bar on the home page only searches datasets. It says that which is fine, but could mislead users as to what is available. Can we add a second search bar for `documents`? Open to other suggestions.

![image](https://user-images.githubusercontent.com/19787025/28167096-5bab9330-67a8-11e7-81f9-c8e948bb6b1f.png)

**Comment by mattfullerton** [comment]
This will get sorted out with #120 but thanks for flagging this as yet another place where the word "dataset" needs to be changed :-)

**Comment by mattfullerton** [comment]
I've added this to the todo list in #120
