### ISSUE TITLE
Splitting EITI summary data file into two?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#13]
We are currently doing some user testing and feedback of the EITI dataset with NRGI country teams. 

One of the questions which came back was that it is not intuitive for users to navigate that Column G and H of the dataset includes “Company payments” and “Recipient agencies” but that these are running in parallel: 
http://resourcedata.org/dataset/eiti-summary-data-table-for-peru/resource/49c618a3-cd07-4d37-8c9f-055fa8dd9bea 

As a user you might think that either field is missing due to errors or missing data while it is actually complete. 

The only intuitive solution I can see to clarify this would be to split the current single CSV file into two separate files: 
-	One file for company payments: Name of company (Column G) 
-	One file for recipient agencies: Name of receiving agency (Column H) 

For project level reporting at Resourceprojects.org we do in fact publish data exactly along the “payment from / payment to” split due to the design of disclosure requirements so to some extent this would make sense. 

I would be interested to hear what you think about this option: pro’s and con’s?

**Comment by mattfullerton** [comment]
Agreed with @anderspeders on Slack to split into two files (CKAN resources)

**Comment by anderspeders** [comment]
Thanks @mattfullerton !

**Comment by anderspeders** [comment]
Confirming new file name format: 

1) "EITI Summary data table - Company payments - [COUNTRY]"
2) "EITI Summary data table - Revenues received by government agencies - [COUNTRY]"

In addition here is a change request for the fllowing header: 
From "name_of_receiving_agency" --> "government_agency_name"

**Comment by mattfullerton** [comment]
:+1:

**Comment by mattfullerton** [comment]
Can @NRGI/vitamin confirm that if the script is updated Thursday that it can be manually triggered in time for your presentation, @anderspeders ?

**Comment by anderspeders** [comment]
In addition to the split file it would would be great at some point *in the future* to explore the following route for creating just one file. Please see instructions from Development Gateway below. 

There's a chance to eliminate the double counting in the flattened files under the following conditions:
1 - The Excel sheet should have disaggregated company information.
2 - The Government reported revenue and the Company reported revenue should match.
3 - Then you group by GFS Code + Name of revenue stream 
4 - The rows of type "company" in column G aggregated by value_reported should be equal to the row of type "government" same column.
If all those conditions are met, then you can copy the value in column name_of_recieving_agency from the "government"type row, to the "company" type rows that have it empty, and delete the former, effectively eliminating the double counting.

**Comment by iprunache** [comment]
@mattfullerton sorry for missing this, the NRGI/vitamin team seems to be empty so we're not being tagged. Please use @NRGI/vitaminsoftware instead.

If the eiti-harvester changes can still be run in the container we use then we can easily build a new image and trigger a manual run, just let us know when.

**Comment by mattfullerton** [comment]
@anderspeders Can you check that this is what you'd like?
http://li1486-99.members.linode.com/dataset/eiti-summary-data-table-for-afghanistan

If so then the script is good to go and I will send it over

**Comment by anderspeders** [comment]
As for the file naming convention I would like an idea for a shorter name that still captures the essentials as the current file name appear too long. Do you have suggestions?

![image](https://cloud.githubusercontent.com/assets/1101585/25274920/997241de-2660-11e7-82e0-9b52947c5f01.png)

**Comment by mattfullerton** [comment]
Your suggestion right there looks good

**Comment by anderspeders** [comment]
Excellent - please implement for across the ~48 EITI summary datasets including the full summary data table (which includes all countries in one).

**Comment by mattfullerton** [comment]
Yes I will apply; are you demoing our staging site or resourcedata.org?

Here it is now:
http://li1486-99.members.linode.com/dataset/eiti-summary-data-table-for-afghanistan

We could further shorten and drop the country name. We know that from the dataset title and the filename (which has the country name) is unaffected. WDYT?

**Comment by anderspeders** [comment]
I think it is good to keep the country within the name. 

I would like to circulate it to staff on ResourceData.org. What are the constraints on this.

**Comment by iprunache** [comment]
The only constraint I can think of is that the full run of the harvester usually took up to 5h when run in the NRGI cluster. I don't know if it will run faster from Derilinx's machines. So if you need the data today we won't be able to run it twice to correct eventual issues.

**Comment by mattfullerton** [comment]
@iprunache Its about 50% done so far
