### ISSUE TITLE
Add dataset categories to dataset facet search

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#130]
Can we add these as a facet-able option for datasets?

![image](https://user-images.githubusercontent.com/19787025/28167213-d376411c-67a8-11e7-97ed-fd73efeaa059.png)

**Comment by mattfullerton** [comment]
We already do this but its renamed to sub-component. This will all get sorted out once we do #119 (for which I am waiting for the mapping).

**Comment by mattfullerton** [comment]
This is done but will not be too exciting till we get the mapping (#119)
