### ISSUE TITLE
Change "sub-component" to category for documents facet search

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#131]
## Why
On search results page, these are shown as "Sub-component" but on the document page it is shown as "Category"

## What
![image](https://user-images.githubusercontent.com/19787025/28167324-39f2a1e2-67a9-11e7-8bdc-680f92eea516.png)

vs.

![image](https://user-images.githubusercontent.com/19787025/28167340-4c18fab0-67a9-11e7-8b41-6635b4bac797.png)

**Comment by mattfullerton** [comment]
I think you want to change Category to Sub-Component, right? In #119 we are planning to set category to something mapped from question. I'll then make sub-component a field in its own right (assuming you still want it?).

**Comment by moman822** [comment]
Yes, please proceed with that.

**Comment by mattfullerton** [comment]
Fixed
