### ISSUE TITLE
Document "Source" link- confusing

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#132]
Intuitively this would take someone to say a government website, but it actually returns some API call of pure JSON, which will likely confuse 99% of users (I don't actually know what the point is). Is this correct? Should we rename it or provide further explanation?

![image](https://user-images.githubusercontent.com/19787025/28167477-be606d88-67a9-11e7-87cf-9e7f492b7f40.png)

to...
![image](https://user-images.githubusercontent.com/19787025/28167536-e8525eda-67a9-11e7-9992-ca9a674840b1.png)

**Comment by mattfullerton** [comment]
I know what you mean. Its only a source as far as our importer, in a very technical way, is concerned.

It would be better, for the example of https://s3.amazonaws.com/rgi-documents/0f589b2add7c2a82a12c960ed04bff9a52941b99.pdf we should take source as the source from the API - http://www.planalto.gov.br/ccivil_03/leis/L8666cons.htm

Right?

(based on http://rgi.nrgi-assessment.org/api/public/documents/BRA-2016-HY)

**Comment by mattfullerton** [comment]
We have the same issue on EITI (in the sense that the user is confronted a wadge of JSON) - but there it really is the source. Can that stay the way it is?

**Comment by moman822** [comment]
@mattfullerton It is ok for the EITI data. For RGI docs, can we use the source from the API (which looks like a link to an external site)?

**Comment by mattfullerton** [comment]
Some RGI docs don't have a source (e.g. http://rgi.nrgi-assessment.org/api/public/documents/LBR-2016-MI) - I'm going to fall back to the API link for that and change the label to "Source or API link"

**Comment by mattfullerton** [comment]
Fixed on the import and labelling sides
