### ISSUE TITLE
Use a hosted SOLR instance instead of a SOLR container for the CKAN site

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#14]
@iprunache commented on [Mon Jan 30 2017](https://github.com/NRGI/nrgi-dcos/issues/207)

## Why
Ensure that SOLR data is not lost when CKAN tasks are restarted or deployed. Without SOLR data the www.resourcedata.org site would show no available datasets.

## What
- [x] an external, hosted, SOLR instance is used for www.resourcedata.org instead of a container running the SOLR instance

## Notes

---

@iprunache commented on [Fri Apr 07 2017](https://github.com/NRGI/nrgi-dcos/issues/207#issuecomment-292485061)

NRGI is just starting to add custom datasets to the CKAN datastore. Unlike the EITI datasets which are imported automatically these new datasets may be done manually and will be difficult to redo them when we switch to a different SOLR solution. We'll have to act faster with the switch to have as few of these datasets to migrate as possible.

**Comment by aismail** [comment]
We need to confirm that the SOLR index can be rebuilt from the uploaded resources.

**Comment by mattfullerton** [comment]
Yep,
paster --plugin=ckan search-index rebuild --config=/etc/ckan/....ini

**Comment by anderspeders** [comment]
What is the status here?

**Comment by iprunache** [comment]
@anderspeders we'll have this ready by the end of the week.

**Comment by pax162** [comment]
@iprunache based on the provider analysis I decided to go with https://www.measuredsearch.com/.
Analysis is here: https://docs.google.com/spreadsheets/d/1S__LDIdBfZSeqGU1oq7Z_Ip6z6_YqMcTSIqcd4cTBFM/edit#gid=0

**Comment by pax162** [comment]
@iprunache, documentation for how to setup the solr:
- Follow steps 1-3 from this quickstart guide: https://www.measuredsearch.com/docs/ 
- After you unzip the archive downloaded from point 3 in the guide, you will need to overwrite the schema with the ckan one. The ckan solr schema can be found at `ckan/config/solr/schema.xml` in the project. Copy the `schema.xml` file over the `searchstax-client-master/solr-5/configsets/basic_configs/conf/schema.xml` file, where `searchstax-client-master` is the root of the folder unzipped at point 3 from the guide.
Something like this: 
```
cp ~/nrgi-resourcedata.org/ckan/config/solr/schema.xml searchstax-client-master/solr-5/configsets/basic_configs/conf/schema.xml
```
- Now continue executing the instructions from the guide. 
- At point 4 in the guide this is the command we used (you have to be in the scripts folder, as mentioned in the guide):
```
./zkcli.sh -zkhost ss288577-1-zk-us-east-1-aws.measuredsearch.com:2181 -cmd upconfig -confdir ../configsets/basic_configs/conf/ -confname ckan
```
- At point 5 we run two commands to create the collections, one for master, one for staging
- master:
```
curl 'https://ss288577-us-east-1-aws.measuredsearch.com/solr/admin/collections?action=CREATE&name=master&collection.configName=ckan&numShards=1'
```
- staging:
```
curl 'https://ss288577-us-east-1-aws.measuredsearch.com/solr/admin/collections?action=CREATE&name=staging&collection.configName=ckan&numShards=1'
```
And this should finalize the config. To test the indexes you can use these links:
staging:
```
curl https://ss288577-us-east-1-aws.measuredsearch.com/solr/staging/query
```
master:
```
curl https://ss288577-us-east-1-aws.measuredsearch.com/solr/master/query
```

Note that we have no authentication, if someone knows the link they have full admin access.

The steps documented above are already executed. From here on, the ECS services (and optionally the docker-compose file) will have to be modified.

We will have to set the links in the CKAN container definitions. We will use the SOLR_URL variable which will contain one of the two master/staging links below. Use the master link for master, staging link for staging:
master: `https://ss288577-us-east-1-aws.measuredsearch.com/solr/master`
staging:`https://ss288577-us-east-1-aws.measuredsearch.com/solr/staging`

The old SOLR_PORT_8983_TCP_ADDR and PORT variables will be no longer used. Also the solr container will no longer be used.

After the link to the hosted solr is up, we should rebuild the index, as specified by Matt above.

**Comment by pax162** [comment]
Things we have to do to finalize this issue:
- Implement #35 (add staging databases)
- Update the staging resourcedata ECS task definition with the new SOLR_URL variable and database links, probably other things too, the staging definitions is quite old
- Rebuild the index on staging
- Test that the index works on staging, add some datasets and see if they show up in the index, try some searches, perhaps ask Matt for more tests
- Implement #36 (add IP based filtering to the SOLR deployment)
- Test that staging still works after adding the IP filter rules
- Update the production resourcedata ECS definition
- Rebuild the index on production
- Test that everything works on production

**Comment by pax162** [comment]
The IP filtering task is important because CKAN does not support basic http authentication for SOLR. The python module CKAN uses to interact with SOLR is `pysolr`. Details here: https://github.com/ckan/ckan/pull/2352. Here we can see the way in which CKAN calls pysolr:https://github.com/vitaminsoftware/nrgi-resourcedata.org/blob/master/ckan/lib/search/common.py#L67 . The solr_user and solr_password variables are not used, even though they are mentioned in the docs: http://docs.ckan.org/en/latest/maintaining/configuration.html#solr-url

**Comment by iprunache** [comment]
All done.
