### ISSUE TITLE
Incorrect countries displayed

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#142]
Incorrect countries displayed like Congo in the DRC list. 

URL: https://staging.resourcedata.org/dataset?country=theDemocraticRepublicofthe

![image](https://user-images.githubusercontent.com/13888372/29123979-c67487ce-7d17-11e7-931d-10e3a92d769d.png)

**Comment by mattfullerton** [comment]
Are Republic of Congo and DRC two different countries (pardon my ignorance). 

This relates to #41 and probably I've done one mapping wrong/too many.

**Comment by charlesyoung** [comment]
Yep the Democratic Republic of the Congo and Republic of the Congo are two different countries.

**Comment by mattfullerton** [comment]
This will get fixed with the next EITI import
