### ISSUE TITLE
Standardise headings

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#146]
Page headings should be as below. 

![image](https://user-images.githubusercontent.com/13888372/29125024-e36e9538-7d1a-11e7-8779-0d98ef40a8ce.png)

Datasets noted as Dataset on the page heading
Documents noted as Document on the page heading
Organisations and Help seems fine
Analysis is displayed in a completed different way

**Comment by mattfullerton** [comment]
@moman822 Can you decide how to deal with the analysis issue? I'll do the others together with #140

**Comment by mattfullerton** [comment]
@moman822 I think Analysis is covered well enough by #176 and doesn't require any action on your part right now
