### ISSUE TITLE
List countries alphabetically 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#147]
List countries alphabetically 

![image](https://user-images.githubusercontent.com/13888372/29125321-c5349c60-7d1b-11e7-9c51-be88280e1b0f.png)

**Comment by moman822** [comment]
Good catch. Instead though, can we further segment these to NRGI's Priority and Limited Engagement countries with explicit notation?

The top section is good and should explicitly label "NRGI Priority Countries". A section labelled "NRGI Limited Engagement Countries" should followed containing:

* Azerbaijan, Bolivia, Kyrgyz Republic, Libya, Peru, Philippines, Uganda, Ukraine, Zambia

Then all other countries can be listed alphabetically.

![image](https://user-images.githubusercontent.com/19787025/29292287-9a7dc558-8114-11e7-9cf7-e5a6abfd7206.png)

**Comment by charlesyoung** [comment]
Fine if its labeled otherwise users won't understand the breakdown.

**Comment by moman822** [comment]
@mattfullerton 

This is not quite there on staging (understand it isn't closed but)
![image](https://user-images.githubusercontent.com/19787025/30398997-4988b466-98a0-11e7-8f95-d33c14b33485.png)
