### ISSUE TITLE
EITI Complete Summary Data Table

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#148]
The 'EITI Complete Summary Data Table' is added to each country separately like below example for Afghanistan. 

URL: https://staging.resourcedata.org/dataset?country=Afghanistan

**Comment by moman822** [comment]
@charlesyoung I believe this is how we want it as the Complete table includes (and is tagged with in its metadata) every country. So it is not incorrect and it let's users know there is a single EITI dataset with all countries where they otherwise might have missed it.

**Comment by charlesyoung** [comment]
@moman822 not sure that I agree as it skews the number of datasets per country. So Afghanistan is noted as having 2 datasets but one is the 'EITI Complete Summary Data Table' which includes the same data as what is in the 'EITI Summary data table for Afghanistan' table.

**Comment by mattfullerton** [comment]
@charlesyoung I think we need to look at these numbers as what they are: CKAN search summaries of how many datasets have something to do with e.g. Afghanistan

We could of course drop the countries tagging on the complete dataset, but I think its correct that way. I'm highly biased though after all the work to enable tagging with multiple values...

**Comment by charlesyoung** [comment]
The only thing is that the numbers aren't technically correct because the country data is also included in the complete dataset. That said its not the end of the world if it remains as is.

**Comment by mattfullerton** [comment]
We decided yesterday to leave this as it is
