### ISSUE TITLE
Derilinx site

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#149]
Open the Derilinx site in a different window. 

![image](https://user-images.githubusercontent.com/13888372/29131653-d66f8082-7d2d-11e7-8368-de2dd3fe905d.png)

**Comment by mattfullerton** [comment]
Can we just make a general policy decision on whether we're ever going to do this for any links ever? I must admit I'm quite glad of it in some situations on the web (e.g. Gmail) and totally understand why you would want it here, but:

https://css-tricks.com/use-target_blank/

You might have noticed that that link didn't open a new tab for you from GitHub :smile:

**Comment by mattfullerton** [comment]
@moman822 Would appreciate your thoughts on this. I noticed I got sprung into a new tab in Firefox on one of the analysis page links, which wasn't to my taste.

**Comment by moman822** [comment]
@mattfullerton can we do internal links, same tab/external links, new tab?

**Comment by mattfullerton** [comment]
We agreed to leave this as is and discourage opening new tabs/windows in general
