### ISSUE TITLE
Open Oil URL incorrect 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#151]
![image](https://user-images.githubusercontent.com/13888372/29133847-1159645e-7d35-11e7-8fb5-e2f0f5109e9a.png)

**Comment by moman822** [comment]
@mattfullerton I don't see how I can edit this page. Is it not CMS-based?

**Comment by mattfullerton** [comment]
Its here: https://www.resourcedata.org/ckan-admin/config
