### ISSUE TITLE
Incorrect dates

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#152]
URL: https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-senegal/resource/35dbd332-1ce3-4c24-90a6-ee816250009c

![image](https://user-images.githubusercontent.com/13888372/29134372-b1ab8652-7d36-11e7-9f0d-e35a2d35b677.png)

**Comment by moman822** [comment]
@charlesyoung can you expand on what is incorrect about the dates? These are just timestamps provided by the Secretariat so I don't know if we will be able to change them but I also can't see what is wrong with them.

**Comment by charlesyoung** [comment]
Just that it might be confusing to the user. Can we not exclude the timestamp?

**Comment by anderspeders** [comment]
It is included so that users can access the additional information about when the data was added.

**Comment by charlesyoung** [comment]
This is how it comes over in Excel - 2017-06-06T07:01:07+0000. 

Should we not change to something like 2017/06/06  07:01:07 to make it more useful to the user?

**Comment by mattfullerton** [comment]
Let's stick with ISO formatting
