### ISSUE TITLE
Additional info

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#153]
What do below dates signify? 

![image](https://user-images.githubusercontent.com/13888372/29134425-dd82b00c-7d36-11e7-9bb4-b95d4c9f6f1f.png)

I click on 2014 and get [34 ](https://staging.resourcedata.org/dataset?year=2014)datasets. 

However the dates in the Senegal [table ](https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-senegal/resource/35dbd332-1ce3-4c24-90a6-ee816250009c) are for the year 2013 and not 2014. 

Not sure if I'm missing something. 

Also should we not include a date search with the theme, country and format searching options?

**Comment by moman822** [comment]
@charlesyoung these are the years for which there is data. I currently see both years in the Senegal table, can you check and see if the issue you saw has persisted (everything is live now on resourcedata.org so you can look there, not staging).
