### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#155]
Data download works on Staging but not on [Prod](https://www.resourcedata.org/dataset/eiti-summary-data-table-for-cameroon/resource/28001c4a-f8a7-4d05-b8b6-5adffdf970e3). 

![image](https://user-images.githubusercontent.com/13888372/29161780-cfa3a9d8-7db7-11e7-8167-3b57a52c4d2c.png)

**Comment by iprunache** [comment]
@charlesyoung we're doing a deploy today on production that includes a schema change. Resources will not be available until harvesters finish running at about 14:00 UTC.

**Comment by charlesyoung** [comment]
Works after the new deployment.
