### ISSUE TITLE
Wrap metadata tags in Additional info table

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#157]
Can we wrap these left to right and display them from lowest to highest? Same for countries where applicable (A-Z).

![image](https://user-images.githubusercontent.com/19787025/29215244-3b7595de-7e78-11e7-9e71-b33e875ec0ba.png)

**Comment by mattfullerton** [comment]
That ought to be doable (note to self: do on template, no guarantee that our import is the only one in the long term and creates the overhead of rerunning imports, esp. RGI).
