### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#160]
Should we not add an explanation mouseover for the different themes as its not clear what they each represent?  
![image](https://user-images.githubusercontent.com/13888372/29305601-ddbe50be-8199-11e7-9e28-0d7569a7d718.png)

Also do we not want to add a doc total per theme seeing that most are empty and will waste the users time clicking on each theme only to realise there are no associated docs? 
![image](https://user-images.githubusercontent.com/13888372/29305999-b324615c-819b-11e7-875a-f3725053302a.png)

**Comment by mattfullerton** [comment]
See #119 which is still unresolved cc. @moman822 @anderspeders

**Comment by mattfullerton** [comment]
@moman822 @anderspeders Would be good to hear from you if you want numbers or mouseovers; if not we can close this as the underlying issue is #119

**Comment by moman822** [comment]
@mattfullerton 

Numbers would be best. How involved will this solution be?

**Comment by mattfullerton** [comment]
I'll probably delegate to @jodiegardiner for the numbers, but getting them is easy enough. We do something similar here:
https://github.com/derilinx/ckanext-nrgi-published/blob/master/ckanext/nrgi/plugin.py#L65
