### ISSUE TITLE
Datasets not tagged 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#162]
There seem to be 4 datasets that haven't been tagged. 

![image](https://user-images.githubusercontent.com/13888372/29306360-8820f392-819d-11e7-8c27-88565eb3d5f2.png)

**Comment by moman822** [comment]
Tagging a Theme is optional, so this can happen. We are undergoing some updates to some of the datasets.

**Comment by charlesyoung** [comment]
Should tagging a theme not be required rather than optional?
