### ISSUE TITLE
Country name spelling

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#163]
Cannot see this logged but country names theDemocraticRepublicofthe and C\u00f4ted'Ivoire obviously needs to be updated. 

Also countries consisting of more than one word are joined like SaoTomeandPrincipe and CentralAfricanRepublic.

**Comment by moman822** [comment]
To expand:

The issue appears for Datasets & Documents only in the facet search sidebar:
![image](https://user-images.githubusercontent.com/19787025/29378902-bc15f520-828e-11e7-961b-c8f0889e4540.png)


The search does not work for Cote d'Ivoire
![image](https://user-images.githubusercontent.com/19787025/29378991-03842cd8-828f-11e7-90f9-d8dbe37e771d.png)

However, the Cote d'Ivoire dataset is still tagged to this value but only in one direction:
![image](https://user-images.githubusercontent.com/19787025/29379088-3fc7cd94-828f-11e7-98d2-b498fefa196e.png)

**Comment by mattfullerton** [comment]
Needed to improve the parsing of these multi-valued fields before they go into the index; I had been concentrating on questions before and oversaw the damage I was doing to country names.

Here's the result now:
http://li1665-139.members.linode.com/dataset?_country_limit=0&country=Congo%2C+the+Democratic+Republic+of+the
http://li1665-139.members.linode.com/dataset?_country_limit=0&country=C%C3%B4te+d%27Ivoire

@iprunache We will need to rebuild the SOLR index on staging, then production. No new imports are required.
