### ISSUE TITLE
Change all occurrences of ResourceData to ResourceData.org (was: ResourceData or ResourceData.org)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#166]
Need to decide if we use ResourceData or ResourceData.org throughout the site. 

Also a text error below. 

![image](https://user-images.githubusercontent.com/13888372/29308062-a2e13514-81a4-11e7-8b10-a0aa8653e683.png)

**Comment by anderspeders** [comment]
ResourceData.org - would be my suggestion.

**Comment by moman822** [comment]
We currently have it as ResourceData on the front page. Should we change that as well?

ENERGYDATA.info seems to do this:
![image](https://user-images.githubusercontent.com/19787025/29379656-270aad7e-8291-11e7-91df-b68b578f825e.png)

**Comment by anderspeders** [comment]
Let me check and get back to this thread.

**Comment by charlesyoung** [comment]
We use ResourceProjects.org and ResourceContracts.org for our other sites.

**Comment by anderspeders** [comment]
Yes, ResourceData.org is confirmed

**Comment by mattfullerton** [comment]
@moman822 If you can do any content items, I'll do any places that are hard-coded

**Comment by mattfullerton** [comment]
@moman822 I don't find any hard-coded places

**Comment by moman822** [comment]
Ok closing for now.
