### ISSUE TITLE
Download URLs changing

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#169]
I have noticed that the download URLs are changing and do not always work one day to the next.

Example: I copy the URL to use in a script and it runs. I come back the next day and it does not. I copy the URL for the same resource again and compare; they are not the same. 

This part changes:

...a6f3c0344892/resource/**9823fe38-fc32-4f8f-acc9-e18e5ad3f36f**/download/company-payments-peru.csv

Is this expected? Intentional? Unavoidable? I assume it is related to the import.

![image](https://user-images.githubusercontent.com/19787025/29380608-4ae0705a-8294-11e7-8cd8-74314ca45789.png)

**Comment by mattfullerton** [comment]
This was an issue but shouldn’t be any more for EITI datasets (where we are rerunning the import). See Issue #88 

Suggest closing.

**Comment by iprunache** [comment]
Could be related to #168

**Comment by moman822** [comment]
Nigeria company payments from today:

`https://www.resourcedata.org/dataset/985f7808-e561-417f-85bd-13ef26d794f2/resource/16ce1e53-d200-4bbe-beb7-2fa61370ce1d/download/company-payments-nigeria.csv`

It is different.

**Comment by iprunache** [comment]
Different url today too:
```
https://www.resourcedata.org/dataset/985f7808-e561-417f-85bd-13ef26d794f2/resource/3e05fe1c-a197-4e54-8a88-16714f32f203/download/company-payments-nigeria.csv
```

Looks like the harvesters is always re-uploading the resources. @mattfullerton how can we validate this assumption?

**Comment by moman822** [comment]
Interestingly the API seems to be changing as well, but the calls are still working:

I pulled this on Friday for Complete Summary Data government payments:
`https://www.resourcedata.org/api/action/datastore_search?resource_id=df2bb52d-f765-4607-8f5e-7dd13364804c&limit=5`

and this from today:
`https://www.resourcedata.org/api/action/datastore_search?resource_id=b5bfbd2c-2f4a-4704-ae60-576422364ec2&limit=5`

They return the same response except for a different resource ID and a 2 second difference on the timestamp.

**Comment by mattfullerton** [comment]
Sorry guys for all the searching you've been doing whilst I was away; the "don't replace" feature was accidently disabled (I wanted it disabled for the first fresh run, and haven't pushed the correct version):

https://github.com/NRGI/resourcedata.org/blob/master/harvesters/eiti/scripts/eiti_import.py#L100

Not likely to be related with #168

**Comment by mattfullerton** [comment]
This problem is still there or has returned

**Comment by mattfullerton** [comment]
On hold until #195 is sorted

**Comment by mattfullerton** [comment]
This would appear to be sorted. Test case is eiti-summary-data-table-for-liberia:
https://www.resourcedata.org/dataset/eiti-summary-data-table-for-liberia/resource/9cfaf15e-c4db-46a2-8e47-23cfebe97ea3

I checked this link on 9th October, on 10th October it was updated (package_patch) and the link still works.

Note that the missing table is covered by #199
