### ISSUE TITLE
Remove last comma in series

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#172]
On the front page:

"...oil, gas and minerals."

"Strategy, Consultation and Institutions"

![image](https://user-images.githubusercontent.com/19787025/29472006-3c6d2c6a-8420-11e7-8ded-9c7aa8e9534b.png)

In the footer:

![image](https://user-images.githubusercontent.com/19787025/29472079-81052c7e-8420-11e7-8a25-402094684b1a.png)

**Comment by mattfullerton** [comment]
Just want to note that although I've done this, the "Strategy, Consultation and Institutions" one meant a datasets/documents schema change. There were no documents or datasets filed under that but just flagging in case this has repercussions for NRGI themes being used elsewhere in NRGI.
