### ISSUE TITLE
Fix blue bar for "Analysis" page

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#176]
This blue bar is a different width than other tabs. It is the same for all "Pages" user-created pages.

Can we incorporate the file structure style from other pages somehow?

![image](https://user-images.githubusercontent.com/19787025/29473373-a5afd0ce-8425-11e7-87a9-567e46a54ba7.png)

**Comment by mattfullerton** [comment]
This might be the pages extension not being in-sync with the new Bootstrap stuff in core ckan

**Comment by mattfullerton** [comment]
cc. @jodiegardiner Maybe you can have a quick look at the styles and tell me if its an easy fix

**Comment by mattfullerton** [comment]
What's actually happening here is the breadcrumbing for the pages extension is missing

**Comment by mattfullerton** [comment]
Ha! https://github.com/ckan/ckanext-pages/issues/45

**Comment by mattfullerton** [comment]
Fixed in derilinx fork of ckan-pages and PR'd to ckan version. We may well end up overriding it when we do #184
