### ISSUE TITLE
"Datasets" tab highlighted when looking at RGI documents

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#177]
See: https://www.resourcedata.org/dataset/rgi-environmental-assessments-webpage

![image](https://user-images.githubusercontent.com/19787025/29634129-c77054b4-8816-11e7-96fd-cbd02843707a.png)

**Comment by mattfullerton** [comment]
More a note to myself:
The problem here is again url creation not utilising the package_type. I have an ongoing pull request discussion with a ckan core developer on how to resolve it. I can't get his proposed fix to work. That's in another place in the code, but the issue here is the same.

**Comment by mattfullerton** [comment]
Fixed in our extension and also added to the ongoing CKAN PR
