### ISSUE TITLE
Reconcile payments from companies with receipts to government agencies

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#18]
## Why
For EITI country datasets which have high data accuracy there is an opportunity to "merge" payments and receipts datasets without reducing the amount of infromation. 

The guidance below shows how - thanks to Fernando from Development Gateway for this tip!

I suggest that we develop a tool that will check if a flat file can be produced that include both payments from and payments to and in that case this should supplement the double file for a given country. 

## What
There's a chance to eliminate the double counting in the flattened files under the following conditions:
1 - The Excel sheet should have disaggregated company information.
2 - The Government reported revenue and the Company reported revenue should match.
3 - Then you group by GFS Code + Name of revenue stream
4 - The rows of type "company" in column G aggregated by value_reported should be equal to the row of type "government" same column.
If all those conditions are met, then you can copy the value in column name_of_recieving_agency from the "government"type row, to the "company" type rows that have it empty, and delete the former, effectively eliminating the double counting.

**Comment by mattfullerton** [comment]
This is the same as #28 right?

**Comment by mattfullerton** [comment]
Closing in favour of #28
