### ISSUE TITLE
New dataset resources returning Server Error

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#180]
Tried to add simple CSV file as a new dataset, clicking on the resource dead-ends to Server Error page:

https://www.resourcedata.org/dataset/sample2

Tried to add another one to datastore, same result:

https://www.resourcedata.org/dataset/resource-revenue-data

**Comment by moman822** [comment]
This is "fixed" by setting the dataset to Public; not sure if there is something deeper to look into but it is not urgent now.

**Comment by mattfullerton** [comment]
I can't really replicate this - can you try again and show screenshots/exact set of steps?

What I am seeing is that pushing to datastore is failing (Error 500 in the error text) and with a 2nd push it fails. However when i switch from public to private that works (both with initial creation and with a push after failure and after switch). I'm not sure if datapusher/datastore works for private datasets (it has to grab the resource, and I would have thought it gets passed the current user's API key to help it do that, but I'm not sure).

I don't think looking into the datapushing-when-private is worth it, but anything that dumps your browser into an Error 500 screen is, so let me know if you can reproduce it.

As mentioned in #145 - I'd like to know what version of datapusher we're using @iprunache

**Comment by mattfullerton** [comment]
Ah, and, importantly, I don't get this error on our development setup, even with private dataset

**Comment by moman822** [comment]
It is not happening now. Wouldn't worry about the datapusher issue either. Close if there is nothing further.
