### ISSUE TITLE
Change Analysis URL path

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#184]
Replace "Pages" with "Analysis". Depending on ease of implementation.

![image](https://user-images.githubusercontent.com/19787025/29924965-ce747ac6-8e2c-11e7-9da0-553773575158.png)

**Comment by mattfullerton** [comment]
I'm fairly certain this is easy to do; will get back to you if not

**Comment by mattfullerton** [comment]
@moman822 This is done now on staging. You'll need to change your links in the landing page and I still need to change the menu and the title on the page for the second link below

But, the hard work is done:
https://staging.resourcedata.org/analysis/analysis-landing-page
https://staging.resourcedata.org/analysis/

I've tried to only change links for public facing/linked-to pages. Its done properly so it can be accepted back into ckanext-pages (the idea of an alternative name for pages as a configuration property for CKAN)

**Comment by moman822** [comment]
Not knowing what you plan to change on the menu and title of `/analysis`, these are my thoughts/concerns:

Here is `/analysis/home` (changed `analysis/analysis-landing-page` to `analysis/home`)
![image](https://user-images.githubusercontent.com/19787025/30881223-095d837a-a2d3-11e7-864e-5f899ebf5c5f.png)

If you click the second `Analysis` link on the breadcrumb bar, it stays, as expected.

If you click the first `Analysis` link, it takes you here, the "real" home page for this section of the website. This is not desirable.
![image](https://user-images.githubusercontent.com/19787025/30881248-29da58ee-a2d3-11e7-8399-27dbe9f39aca.png)

I don't imagine it is feasible or worth spending time on to hack what is now `/analysis/home` into just `/analysis` and then have subsequent links to pages be also `/analysis/first-analysis-page` (because what is now `analysis/home` is really a page made with the standard CKAN 'Pages' feature branching off `/analysis`).

My original desire was to have `analysis/home` so I could customize the landing page that users would see. Is it possible instead to insert some minimal customization into the default CKAN "Pages" page? Just a paragraph or two, plus the breadcrumbs bar, and have pages created under it with the subsequent breadcrumbs?

Hopefully this will 

That page is now `staging.resourcedata.org/analysis` and looks like this to outside users:
![image](https://user-images.githubusercontent.com/19787025/30881609-5f7fa390-a2d4-11e7-929e-d4fefd1918a7.png)

**Comment by mattfullerton** [comment]
Would it be enough if I just hack the breadcrumbs bar a little bit so that Analysis (top level) always goes to analysis/home, and that if we're on /home, we don't show that as a sub-option, and only do that for other pages?

I can probably also tell /analysis/ to give a 404 for people not logged in and perform as normal (i.e. managers view of what pages exist) for logged in users.

i.e.
/analysis/ - 404, no breadcrumb
/analysis/home - Breadcrumb is "Analysis"
/analysis/some-other-interesting-viz - Breadcrumb is "Analysis" -> "Some Interesting Viz"

and so on

Its obviously a deviation from the core extension, but... that's what open source is for...

**Comment by mattfullerton** [comment]
I've gone ahead and made those changes on staging. You need to update the internal links in pages to /analysis instead of /pages, but overall it seems to be working nicely.

**Comment by moman822** [comment]
@mattfullerton this looks good.

**Comment by moman822** [comment]
@mattfullerton 
This doesn't look good on second thought. The "Analysis" link on the toolbar needs to be updated:

It points to this:
https://www.resourcedata.org/pages/analysis-landing-page

Instead of this:
https://www.resourcedata.org/analysis/home

**Comment by mattfullerton** [comment]
That's already done on staging
