### ISSUE TITLE
Scoping: Link RGI explorer (xls) to RGI Source Library by question ID

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#185]
## Why

Problem / user story: 
As a researcher browsing RGI scores using the RGI Explorer (dynamic macrobased Excel file) I would like to have access to a direct URL for the specific source file that justifies the score. 

So for example - for Ghana's score on 2.2.a I would like to have a direct link between the RGI Explorer and the source URL on ResourceData.org.

How the question ID appear in the RGI Data Explorer: 
![image](https://user-images.githubusercontent.com/1101585/29936948-ed632048-8e51-11e7-8339-ab12bb0ce2d1.png)

How the question ID appear in ResourceData.org:
![image](https://user-images.githubusercontent.com/1101585/29937079-5c5cf24e-8e52-11e7-9164-e7457d93a096.png)

The RGI Data Explorer is available as download here [xls download]: http://resourcegovernanceindex.org/system/documents/documents/000/000/040/original/2017_RGI_Data_Explorer.xlsm?1504014405

@mattfullerton: Would you be able to devote some time for scoping of this - eg. 0.5 day to explorer options for adding deep URL to the RGI data explorer?

**Comment by mattfullerton** [comment]
This looks like it would be very straightforward - you have a template URL of

https://www.resourcedata.org/document?country=[COUNTRY]&question=[QUESTION ID]

And you just replace those two values based on what the user selects.

Is there someone I can talk to who maintains the tool? I don't really have or use Excel.

**Comment by anderspeders** [comment]
@mattfullerton We have developed the excel tool with an external consultant so I'll need to explore availability.

I imagine that the outcome could be a CSV with columns including: 
questions | country | URL

**Comment by moman822** [comment]
@anderspeders I can likely do this

**Comment by anderspeders** [comment]
@moman822 Great! Could you also review the RGI Explorer and propose where the deep links would be inserted to make the most sense?

**Comment by moman822** [comment]
This is done
