### ISSUE TITLE
Document/Dataset breadcrumb bar

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/resourcedata.org#186]
Don't switch to organisation when browsing datasets by type

**Comment by mattfullerton** [comment]
@moman822 
This is standard CKAN behaviour if a dataset belongs to an organization, so I'd be inclined not to mess with it. Can we live with it? It may be useful in the long run when we have combined browsing of datasets - a user sees then under which "box" it is filed.

Example:
Go to demo.ckan.org
Click on datasets
Filter by any organization in the facets (this is just to get rid of unowned datasets)
Click on one of the datasets
Observe breadcrumb bar

**Comment by moman822** [comment]
Sure, that seems fine to me.
