### ISSUE TITLE
RGI docs: country names w/ "of"

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#187]
They are getting split into two facets with the exact same documents tagged:

![image](https://user-images.githubusercontent.com/19787025/30076325-7aa562ca-9246-11e7-9417-9863aa601c58.png)

**Comment by mattfullerton** [comment]
Please check out things on staging (and give me the go-ahead when to push to production). This problem is detailed and solved in #163

**Comment by mattfullerton** [comment]
Sorry @moman822 - the code may be live on staging but it requires a re-index from e.g. @iprunache (see Slack and #163)

**Comment by moman822** [comment]
Not seeing this implemented on staging.resourcedata.org and it looks like the deployment went through on slack

**Comment by mattfullerton** [comment]
I'll leave you in charge of closing or opening the issue, but the code changes are done. Waiting on a re-index from Vitamin.

**Comment by moman822** [comment]
Ok, wasn't sure if you expected that to happen with the deployment or separately. I'll close.
