### ISSUE TITLE
Confirm country names

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#188]
## Why

Per latest email exchange we will need to lock in country names in RGI Source Lirbary in order to add links to Resourcedata.org in an external excel file. 

@mattfullerton please coordinate with @moman822 to ensure that we can relay the final URLs to the developer who is designing the spreadsheet.

**Comment by mattfullerton** [comment]
We decided to use ISO3 codes

**Comment by anderspeders** [comment]
Thanks
