### ISSUE TITLE
Preview vs. More Information

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcedata.org#189]
Why are some tables noted as 'Preview' while others as 'More Information'? 

![image](https://user-images.githubusercontent.com/13888372/30318793-5fcd1d86-97ae-11e7-808c-599423806abe.png)

![image](https://user-images.githubusercontent.com/13888372/30318816-6c9f6186-97ae-11e7-8412-2d3479208563.png)

**Comment by anderspeders** [comment]
Thanks, do you have a link to an example page?

**Comment by mattfullerton** [comment]
This depends on whether the resource in question has a preview or not.

**Comment by charlesyoung** [comment]
This might be a stupid question but why don't all the resources have a preview.

**Comment by mattfullerton** [comment]
It depends on the file type/format and on whether the curator wants the resource to have a preview. Obviously if there's no preview it could be a sign of a deeper problem like #178

**Comment by mattfullerton** [comment]
Closing. Please write in #178 if there is new information on PDF preview creation or open a new issue if there are missing/broken previews elsewhere.
