### ISSUE TITLE
Add *year(s)* in metadata for EITI summary data tables

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#19]
## Why

As a user it would be convenient to know how many years of data is available. 

## What
The solution would be to simply list all years that appear in the data value field: *year* 

For example for Afghanistan data the result in the metadata field would be: "2009, 2010, 2011, 2012"

## Notes

![image](https://cloud.githubusercontent.com/assets/1101585/25275512/b0eab91a-2663-11e7-933a-087929523816.png)

![image](https://cloud.githubusercontent.com/assets/1101585/25275541/d2613f38-2663-11e7-9f26-9c58c4643dbf.png)

**Comment by mattfullerton** [comment]
Possible

**Comment by mattfullerton** [comment]
This is properly possible now as the years field supports multiple values

**Comment by mattfullerton** [comment]
Done: e.g. http://li1665-139.members.linode.com/dataset/eiti-summary-data-table-for-albania
