### ISSUE TITLE
EITI summary data country names

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#190]
## Why

This is not a big issue but it has been looking wrong for quite some time. Any chance we can fix this for the EITI summary files?

Is the origin of the issue that we keep importing these names from the API; in that case would there be a solution for it?

![image](https://user-images.githubusercontent.com/1101585/30346432-b449a654-97d6-11e7-913f-633ca544ea17.png)

Also - thanks to Charles who I think flagged this issue first.

**Comment by mattfullerton** [comment]
This is I think now the 3rd time an issue has been opened on this. We are waiting for Vitamin to reindex the SOLR index for the site. I think there is a delay because @iprunache is on holiday.

**Comment by mattfullerton** [comment]
Now fixed on staging and production - thanks @candrei
