### ISSUE TITLE
Add source document year to metadata of RGI Source Library

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#194]
## Why

We've had a request for additional metadata for the RGI Source Library. What I noticed when reviewing the API was that a fields actually did appear to be available. Please correct me if I am wrong?

I would suggest that we add the following to the RGI Source Library: 
    "title": "Test Doc",
    "type": "policy_document",
    "year": "1996",

2) from this metadata what content do we have: 
- Number of entries with content vs. number of empty for each of the above metadata fields?

Would it be possible to assess this?

Link to API documentation: https://github.com/NRGI/rgi-assessment-tool/wiki/Document-List
[
  {
    "_id": "580887d8612e69c635ef7007",
    "file_hash": "56864463d1585b8b001ae436f0e9b79a61d293a3",
    "mime_type": "application/pdf",
    "s3_url": "https://s3.amazonaws.com/undefined/56864463d1585b8b001ae436f0e9b79a61d293a3.pdf",
    "createdBy": "57f5f4fdd513e7d214aef675",
    "__v": 1,
    "publisher": "o'Really",
    "source": "http://document-source.com/doc.pdf",
    **"title": "Test Doc",
    "type": "policy_document",
    "year": "1996",**
    "status": "submitted",
    "creationDate": "2016-10-20T09:01:12.713Z",
    "last_modified": {
      "modified_by": "57f5f4fdd513e7d214aef675",
      "modified_date": "2016-10-26T02:01:32.960Z"

**Comment by mattfullerton** [comment]
We have agreed to:

- Start using RGI API document year as the year instead of the assessment year
- Store an assessment year (survey year) as a new field and possibly an entire date if we can agree on one
- Store document type from the RGI API
- Store Editor, Publisher and Author from the RGI API

**Comment by mattfullerton** [comment]
Would like to do this together with #119 as they both involve schema changes

**Comment by anderspeders** [comment]
makes sense to me.

**Comment by moman822** [comment]
@mattfullerton we have reviewed the new metadata categories for documents [here](http://li1665-139.members.linode.com/document/rgi-review-of-state-budget-execution-for-9-months-of-2015) and would like some UI changes. I will send a file on Slack that has a final template, let us discuss there.

**Comment by mattfullerton** [comment]
This is viewable on dev: http://li1665-139.members.linode.com/document/rgi-regulations-on-mining-operations-legal-notice-no-19-1995 including the revised template. Will coordinate the push to staging and production with @iprunache

**Comment by anderspeders** [comment]
Looks great, 

Minor correction: Could you please list the precepts in the left column by number (not by the number of appearing documents)?

See below: 
![image](https://user-images.githubusercontent.com/1101585/31338895-042eb814-accf-11e7-9b44-b20b28ef7c8a.png)

**Comment by anderspeders** [comment]
In addition: 

1) Please move the filters *Formats* and *Openness* to the bottom of the filter list as these are the least relevant filters:  

![image](https://user-images.githubusercontent.com/1101585/31338945-2f80d0b0-accf-11e7-8793-e9bb3129f5d9.png)

2) Please rename *Sub-components* to *Natural Resource Charter Precept* or if this is too long *NRC Precept*

**Comment by mattfullerton** [comment]
Will do

**Comment by mattfullerton** [comment]
@anderspeders Where did you find that listing of precepts under sub-component? I can't find this.

**Comment by mattfullerton** [comment]
@anderspeders I couldn't see any of the issues with the facets, but we've done the ordering by number for the precept items - viewable on staging.
