### ISSUE TITLE
Search bar misalignment

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#196]
![image](https://user-images.githubusercontent.com/19787025/31147336-8b227756-a857-11e7-80a9-ee2de2c318b2.png)

**Comment by moman822** [comment]
See the magnifying glass on right

**Comment by mattfullerton** [comment]
This is a CKAN core bug to do with the bootstrap 3 migration - I'm asking them about it - haven't found a quick fix (the quick fix I found broken the search icon on the organization page) yet

**Comment by mattfullerton** [comment]
Well, there is a CKAN bug that misaligns it a little, but the bigger issue was us removing the label above the dataset search bar, combined with not removing it on the organization page.
