### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#197]
Clicking this button:
![image](https://user-images.githubusercontent.com/19787025/31285970-bec9d308-aa8a-11e7-915f-5ac2d9de8e80.png)

On staging, it returns the error shown above:
https://staging.resourcedata.org/dataset/eiti-summary-data-table-for-sao-tome-and-principe/resource/f6f13446-5945-4b2f-818a-53b94f604e96

On production it redirects to `/dataset`:
https://www.resourcedata.org/dataset/eiti-summary-data-table-for-norway/resource/75de6d0a-1c1c-4e73-b992-a0ac3232b830

**Comment by mattfullerton** [comment]
This is a core CKAN bug; I will just remove the button for now (it can return when they fix it)

**Comment by mattfullerton** [comment]
This is back on staging. I'd like us all to do a little more browsing/testing of staging before deploying to master.
