### ISSUE TITLE
When updating RGI source library: Be aware not to change URLs for country code + question due to RGI spreadsheet

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#198]
This is just a reminder to ensure that the URLs for the searches that are used for the RGI spreadsheet. The XLS file utilize as far as I am aware country code plus question ID for generating deep URL links:  
http://resourcegovernanceindex.org/system/documents/documents/000/000/151/original/2017_RGI_English_1.2.3.xlsm?1507047429

@mattfullerton Please do ensure that new deployments of RD.org are checked against this spreadsheet. I assume that this relates to the development side (not Vitamin).  

@moman822 can help clarify questions.

**Comment by mattfullerton** [comment]
Thanks Anders for the reminder. I don't see anything in the current batch of changes that will disturb this but will check with this deployment and include in general tests going forward.

P.S. Us removing the ISO code from the display form for the documents in no way disturbs this; the data is still there but not shown.
