### ISSUE TITLE
No EITI data for DRC

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#20]
## Why

The data field for EITI data from DRC is missing: http://resourcedata.org/dataset?country=Dem.%20Rep.%20of%20Congo

**Comment by mattfullerton** [comment]
See also #8

**Comment by mattfullerton** [comment]
Out of interest (because I think this will get resolved with #25) - how did you get that link? I don't see "Dem. Rep. of Congo" listed in the facets (which is good, they should be based on the data, and we know that the metadata for DRC is broken (cf. #25)

**Comment by mattfullerton** [comment]
Closing in favour of #25
