### ISSUE TITLE
Not all questions showing in facet sidebar

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#200]
Missing 1.1.5a-d (possibly others)

https://www.resourcedata.org/document?_question_limit=0&question=1.1.5a

but

![image](https://user-images.githubusercontent.com/19787025/31406138-561e2efc-adce-11e7-9777-94684b8f6c26.png)

**Comment by mattfullerton** [comment]
We were limiting the list of facets we deal with to 50 by not setting a config option. So despite sorting by name instead of popularity, we still only had the 50 most popular ones to sort.
