### ISSUE TITLE
Should title remain with country, year, sector given that this is in metadata?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#203]
@moman822 It migth be worth exploring this with colleagues after the latest additions of metadata (eg. year). 

![image](https://user-images.githubusercontent.com/1101585/31785818-5e8577c8-b4d4-11e7-8665-71e44fc5d370.png)

**Comment by moman822** [comment]
@mattfullerton what would removing the parentheses and everything in between  involve?

**Comment by mattfullerton** [comment]
@moman822 Just a small change in the EITI import, no big deal

**Comment by anderspeders** [comment]
@mattfullerton Could we implement this on staging? 

@moman822 then we could pass it around to a few colleagues?

**Comment by mattfullerton** [comment]
@anderspeders RGI import, not EITI, but, yes

**Comment by mattfullerton** [comment]
Now live on staging

**Comment by moman822** [comment]
@mattfullerton we are having some buyer's remorse with this, realizing that now you can't tell which country or sector the documents are for without clicking on them.

Can we revert to having just the **country name** and **sector** (oil&gas / mining), leaving year out?

Thanks.

**Comment by mattfullerton** [comment]
We certainly can. Another option would be to use labels (similar to those used for formats at the bottom of each listing) beside the title to show that information (that would be a little more "purist" by not duplicating data across fields).

**Comment by moman822** [comment]
Let's try your suggestion here @mattfullerton

**Comment by mattfullerton** [comment]
@moman822 What do you think?

https://staging.resourcedata.org/document?_question_limit=0

**Comment by moman822** [comment]
This looks really good, adds some pop to the page as well. What is the basis for the coloring of country names-just a unique color per term?

**Comment by mattfullerton** [comment]
This was done some time ago

**Comment by anderspeders** [comment]
Hi @mattfullerton @moman822, I am reopening this as I think we managed to get only half of the ticket addressed. 

The labels on the source library are really nice additions, but that then also enables us to remove the parenthesis text for each document: https://www.resourcedata.org/dataset/rgi-petroleum-act-1934-

@moman822: Correct me if I am wrong but we should remove *(Oil and Gas, Myanmar, 2016)* by now as this info is covered elsewhere, right?

**Comment by anderspeders** [comment]
@moman822 @mattfullerton Just following up here.

**Comment by anderspeders** [comment]
Hi @mattfullerton @moman822 - can we take this forward please?

**Comment by anderspeders** [comment]
this looks to be fixed.
