### ISSUE TITLE
Send email on staging once an hour for testing purposes

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#208]
## Why
For testing purposes , the staging email notification sender should be triggered once an hour.

## What
- [x] the staging email sender is enabled and configured to send email once an hour

**Comment by adinuca** [comment]
This has been done. Also, the eiti harvester has been enabled for Staging

**Comment by anderspeders** [comment]
Next up: 
- @moman822 to facilitate testing 
- deployment

**Comment by mattfullerton** [comment]
We should track this in #139
