### ISSUE TITLE
Set up hostname in resourcedata.org containers to `resourcedata.org`

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#209]
## Why
Reduce the chance that notification emails sent by resourcedata.org are flagged as spam.

## What
- [x] hostname for resourcedata.org containers is set up as `resourcedata.org`
- [x] SPF(https://en.wikipedia.org/wiki/Sender_Policy_Framework) is set up for the `resourcedata.org` domain

## Notes
```
Could you look at getting the hostname set properly for the docker containers? Emails come through with this in the header:
Received: from 10f2eb840d81.localdomain (ec2-52-70-224-61.compute-1.amazonaws.com. [52.70.224.61])

On our test environment I was able to fix this by using the host parameter in the docker-compose file. There seems to be a -h option for docker, not sure how it works on AWS.
Setting up SPF for the resourcedata domains would also be good, if it hasn't already been done
```

Not sure how to configure SPF especially since IPs on ECS container instances can change. The `PTR` mechanism may be what we need.

**Comment by adinuca** [comment]
Tested for the staging container that the hostname is set by modifying the task definition.

**Comment by adinuca** [comment]
Hi @mattfullerton, I have set the hostname for the RD containers to staging.resourcedata.org for the staging instance and resourcedata.org for the production instance.

I am still researching on how to configure the SPF to suit our ECS infrastructure.

**Comment by adinuca** [comment]
From the wikipedia page of SPF:

> If the domain name (PTR record) for the client's address is in the given domain and that domain name resolves to the client's address (forward-confirmed reverse DNS), match. This mechanism is deprecated and should no longer be used.[7]

**Comment by adinuca** [comment]
Quick guide to SPF: http://www.openspf.org/SPF_Record_Syntax
Main page : http://www.openspf.org/Introduction
Specification: http://www.openspf.org/RFC_4408

**Comment by adinuca** [comment]
It is not best practice to send email from localhost(docker container). 
An alternative solution for getting around the SPF issues and following best practices is to use an external mail server. For this, we have configured an AWS SES for resourcedata.org. Next step is to find out how we can configure CKAN or the docker container to use the new mail server.

**Comment by adinuca** [comment]
Based on (CKAN documentation)[http://docs.ckan.org/en/ckan-2.4.9/maintaining/email-notifications.html], email settings can be set using environment variables.

Currently testing with an existing docker container.

**Comment by adinuca** [comment]
CKAN Email settings can be done using the following environment variables:
- CKAN_SMTP_SERVER
- CKAN_SMTP_STARTTLS 
- CKAN_SMTP_USER
- CKAN_SMTP_PASSWORD 
- CKAN_SMTP_MAIL_FROM

This has been tested on Staging.

**Comment by adinuca** [comment]
Asked @mattfullerton to check that emails are sent correctly on Staging. Will close this once we have his confirmation.

**Comment by adinuca** [comment]
This has been deployed to production. If something needs to be changed, we will raise another issue.
