### ISSUE TITLE
Set up CKAN to use basic auth for SOLR

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#211]
## Why
The version of CKAN that we are currently using supports basic auth with SOLR.

## What
- [ ] CKAN connects to SOLR using basic auth

## Notes
resourcedata.org is served by the docker container built from https://github.com/derilinx/ckan-docker-public.
The version of CKAN currently in use is 2.7.2 that allows basic auth: http://docs.ckan.org/en/ckan-2.7.2/maintaining/configuration.html.

Instructions on how to enable Authentication for SOLR server can be found [here](https://www.searchstax.com/docs/security/#solr). A restart of SOLR will be needed.

**Comment by EricSoroos** [comment]
@adinuca Is this still an issue?

I believe that this can be handled by adding environment variables to the runtime configuration of the docker container -- `CKAN_SOLR_USER` and `CKAN_SOLR_PASSWORD`.  It appears that ckan pulls in those variables directly, but if it doesn't we can read those values and write them to the config file.

**Comment by adinuca** [comment]
Hi @EricSoroos , this issue is actually for us, to pass the username and password for SOLR to the docker container and to enable it in SearchStax.

**Comment by adinuca** [comment]
@cmovz , the environment variables for each container are stored in nrgi-dcos repository. 
The SOLR provider is searchstax, you can find credentials in LastPass. If you need to access it locally, you will need to whitelist your IP.

**Comment by adinuca** [comment]
I did not realise this requires downtime: https://www.searchstax.com/docs/security/#solrauth

**Comment by cmovz** [comment]
Trying to build CKAN I get the following error:
```
Command python setup.py egg_info failed with error code 1 in /usr/lib/ckan/default/build/mox3
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c $CKAN_HOME/bin/pip install --upgrade -r $CKAN_HOME/src/ckan/dev-requirements.txt' returned a non-zero code: 1
```

**Comment by adinuca** [comment]
> Trying to build CKAN I get the following error:
> 
> ```
> Command python setup.py egg_info failed with error code 1 in /usr/lib/ckan/default/build/mox3
> Storing debug log for failure in /root/.pip/pip.log
> The command '/bin/sh -c $CKAN_HOME/bin/pip install --upgrade -r $CKAN_HOME/src/ckan/dev-requirements.txt' returned a non-zero code: 1
> ```

@cmovz with docker?

**Comment by adinuca** [comment]
This is actually not needed, we are already restricting access to SOLR based on IP.
