### ISSUE TITLE
List of suggested improvements for EITI API

### ISSUE THREAD

**Issue by deirdrelee** [NRGI/resourcedata.org#213]
## Why
In prep for EITI call 

## What
- Standardise field values, e.g. year_start and year_end as ISO 8601 standard YYYY-MM-DD (e.g. 2015-01-01), 
- Incomplete 'country resource' data
- Use standard URIs, e.g. for company identifiers
- Potentially add missing fields, e.g. commodity field, company ID
- 
- 
- 
- 

## Notes
@all please feel free to add to the list above

**Comment by mattfullerton** [comment]
Closing?
