### ISSUE TITLE
Determine level of usage of resource-data-store since September 2017

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#215]
## Why
Since October 2017 there have been unusual high costs for resource-data-store deployment. This happened because the deployment was scaled up to 232GB automatically but was never scaled down when the usage decreased. We need a way to determine what was the usage of the Compose deployment since September 2017 to have arguments for asking for a refund from Compose.

## What
- [x] Papertrail logs are analysed and data is gathered about the operations on resource-data-store
- [x] other ways of gathering data are researched
- [x] gathered informations are sent to Compose

**Comment by adinuca** [comment]
Article on what Compose say about their PostgreSQL plan and the example with the WAL : https://www.compose.com/articles/compose-notes-for-postgresql-9-5/ .

**Comment by adinuca** [comment]
The usage of datastore_create and datastore_delete doesn't explain the scaling up of the postgresql deployment. We have extracted these informations from the Papertrail logs. The graph of these operations can be found [here](https://docs.google.com/spreadsheets/d/1qDBJOZPFV6QipgvC8UNpNy85T1T2NXOiC8YCG11cLGw/edit#gid=0).

The WAL is written for each write on the database, so next step is to determine if there were other events that could have caused a high number of writes on the database in a short amount of time which would generate many log files.

**Comment by iprunache** [comment]
Nice graph!


[image: Vitamin Software Logo]

*Ionut Prunache*
ionut@vitaminsoftware.com
Software Engineer
vitaminsoftware.com <http://www.vitaminsoftware.com/>

**Comment by adinuca** [comment]
Audit logs from 28th of September:
```
    {
        "id": "59cce9c1327ff6000e14a40a",
        "account_id": "54c285b9636f6d009a470000",
        "user_id": null,
        "deployment_id": "5819c9cc09da8e0016000004",
        "cluster_id": "572dee2d71133800160006ae",
        "created_at": "2017-09-28T12:23:29.756Z",
        "data": {
          "deployment": "resource-data-store",
          "cluster": "us-east-1_4",
          "units": "64",
          "memory": "6.38 GB",
          "storage": "64 GB"
        },
        "email": null,
        "event": "deployment.scale.members",
        "ip": "",
        "user_agent": null,
        "_links": {
          "self": {
            "href": "/audit_events/59cce9c1327ff6000e14a40a{?embed}",
            "templated": true
          }
        }
      }
      {
        "id": "59ccf7d59b89650013cb5f09",
        "account_id": "54c285b9636f6d009a470000",
        "user_id": null,
        "deployment_id": "5819c9cc09da8e0016000004",
        "cluster_id": "572dee2d71133800160006ae",
        "created_at": "2017-09-28T13:23:33.355Z",
        "data": {
          "deployment": "resource-data-store",
          "cluster": "us-east-1_4",
          "units": "232",
          "memory": "23.11 GB",
          "storage": "232 GB"
        },
        "email": null,
        "event": "deployment.scale.members",
        "ip": "",
        "user_agent": null,
        "_links": {
          "self": {
            "href": "/audit_events/59ccf7d59b89650013cb5f09{?embed}",
            "templated": true
          }
        }
      },
```

**Comment by adinuca** [comment]
Log files are available only from the 5th of February 2018.

Above informations were retrieved from their API: 
[https://api.compose.io/2016-07/deployments/5a786a5ec92efc001176cd30/logfiles?start_date=12-01-2018](https://api.compose.io/2016-07/deployments/5a786a5ec92efc001176cd30/logfiles?start_date=12-01-2018)
and [https://api.compose.io/2016-07/audit_events?older_than=2017-10-10&newer_than=2017-09-20&limit=100](https://api.compose.io/2016-07/audit_events?older_than=2017-10-10&newer_than=2017-09-20&limit=100)

**Comment by adinuca** [comment]
Memory usage got to 1.99GB at 10 AM (UTC) today. There is no correlation between the CKAN API calls and the memory usage.

**Comment by iprunache** [comment]
@adinuca can we find actual disk usage from the API? Maybe we have historical data too.

**Comment by adinuca** [comment]
I will double check before answering this, but I don't think we have data going that far.

**Comment by iprunache** [comment]
We could look at the Papertrail logs to see if we had something running between `2017-09-28T12:23:29.756Z` and `2017-09-28T13:23:33.355Z` when the last 2 scalings occurred. Really strange to go from 32 GB to > 128GB in one hour.

**Comment by adinuca** [comment]
I have also checked Slack conversations, in 27-28-29 September, there was a CKAN update and the change to use 2 Postgresql users, one for writing and one for reading.

**Comment by adinuca** [comment]
To see the metrics for a longer period of time(15 months) you need to select 1 hour as data point.

**Comment by adinuca** [comment]
Post actions from the 28th of September 2017 : 
[28SeptPOST.log](https://github.com/NRGI/resourcedata.org/files/1780427/28SeptPOST.log)

**Comment by adinuca** [comment]
Last backup available is from the 1st of December 2017.

**Comment by adinuca** [comment]
Checked the oldest deployment backup, and the size of the backup is 18GB, so at least since the 1st of December we are paying too much. The backup also contains the WAP logs.

**Comment by iprunache** [comment]
Great find with the backup sizes @adinuca! I think we have a compelling case by combining the POST log, AWS metrics and backup sizes. Would you like to ping Compose for an update and present them your findings? I think we should continue the conversation from Frank's account.

**Comment by iprunache** [comment]
By POST log I meant the graph you built that shows the number of datastore creates and deletes since September.

**Comment by adinuca** [comment]
It is exactly what I am doing now :).

**Comment by adinuca** [comment]
Following email was sent to Compose: 
```
Hello, 

We did more digging into the scaling as we couldn't find any explanation (business wise) why this was required in the first place.

We queried the audit events from Compose API and we found out that the resource-data-store deployment has been scaled twice in the same day; we analyzed the metrics and logs that we have at our end and we could not find any reason for the scaling to happen on the 28th of September.

We have gathered information about the activity (access logs) of the application that is using the resource-data-store deployment since around the 28th of September and we could not find any anomalies compared to the days before and after. Our understanding is that the WAL is generated when there are writes on the database; as you can see in the PDF attached, the amount of writes for 28th of September does not stand out.

We also retrieved metrics for the application that interacts with resource-data-store and nothing is out of the ordinary there either (attached AWS metrics).

We also looked at the oldest backup (1st of December 2017) and the size of the DB is 18GB which is similar to the newest backups and proves that at least at that time, we were using less than 20GB.

There is no evidence on our side that suggests the scaling up was necessary and we would appreciate if you could give us any data to support it in order to understand what has happened.

I hope all the above information will be taken into consideration when making a decision about the reimbursement.
Thank you
```
