### ISSUE TITLE
Investigate if the data from resource-data-store is managed correctly

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#218]
## Why
On the 28th of September 2017, the resource-data-store PostgreSQL DB was scaled up to 232GB because of increased disk usage. To keep the costs low, we need to optimize the way data is managed and to remove unneeded data from the DB.

## What
- [ ] database is checked for duplicate datasets
- [ ] obsolete data is removed
- [ ] followup issues are raised to optimise the creation and removal of datasets if needed

## Notes
- monthly logs from Papertrail show that we do  ~400 dataset_create calls and ~150 dataset_delete calls  
- browsing the `resource-data-source` tables shows there are duplicate datasets (look for those with 77 rows)

**Comment by EricSoroos** [comment]
@adinuca Is this still an issue after moving to AWS for the database? If it is, can you check to see what how much storage is in-use for the datastore database?

**Comment by adinuca** [comment]
Hi @EricSoroos, at the moment around 18-19 GB are  used and it has been like that for the last 2 weeks. At the moment this is no longer a problem but it would be good to clean up the data if there really is obsolete data.

**Comment by adinuca** [comment]
There haven't been any issues since moving to AWS. Closing this.
