### ISSUE TITLE
Include question title in data description

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#22]
## What

Would it be possible to add the question title to the description of each file in order to make it easier for users to navigate? 
![image](https://cloud.githubusercontent.com/assets/1101585/25364630/c04f8cac-2931-11e7-90ba-34f79e74de5a.png)

**Comment by mattfullerton** [comment]
That's possible

**Comment by anderspeders** [comment]
I think that would make sense to add. Please proceed.

**Comment by mattfullerton** [comment]
Done
