### ISSUE TITLE
Move ckan PostgreSQL databases for RD from Compose to AWS

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#221]
@adinuca commented on [Mon Apr 02 2018](https://github.com/NRGI/nrgi-dcos/issues/276)

## Why
We want to move away from Compose as their customer support is not the best and they to not have an alerting system to let you know if your deployments have scaled up. This has caused huge unexpected invoices in the past.

## What
- [x] A PostgresSQL instance is set up for ckan-staging
   - [x] instance is created in AWS
   - [x] users are created for the new instance
   - [x] data is migrated from Compose to the new instance
   - [x] RD staging is configured to use the new database
- [x] A PostgresSQL instance is set up for ckan(production)
   - [x] instance is created in AWS
   - [x] users are created for the new instance
   - [x] data is migrated from Compose to the new instance
   - [x] RD production is configured to use the new database 

## Notes
- we should collaborate with derilinx to make sure the new instances correspond to the needs of RD
- Tommy should be informed when the switch for Production is made, to make sure there are no changes between the moment we migrate the data till we do the switch
- the name of the deployment in Compose is resource-data
- PostgreSQL version is 9.4.15
- size of both ckan and ckan-staging is under 1.5 G

**Comment by adinuca** [comment]
We cannot create a dump of the postgresql databases from compose. We could create a backup, restore it locally, create dump and upload it on AWS.

**Comment by adinuca** [comment]
Beta environment was created to test staging.

To migrate the data I did the following: 
- download the last backup
- start postgres 9.4 passing the backup folder as the data folder : 
`postgres -D ~/Downloads/data/backup/20180407125350/snapshot/conf/`
- dump the database:` pg_dump --file="~/Desktop/ckan_staging.sql" --dbname=ckan-staging`
- import the database in staging: `psql --file="~/Desktop/ckan_staging.sql" ckan-staging`

**Comment by adinuca** [comment]
Steps for migrating to production: 
1. Install postgresql version 9.4(You can download it through https://www.openscg.com/bigsql/postgresql/archive-packages/). This will install it in  ~/PostgreSQL/pg94 . You can add postgresql to $PATH.
2. Build new PostgreSQL instances in AWS
  - Login to AWS( credentials in LastPass)
  - Go to RDS -> Instances
  - Launch DB Instance -> PostgreSQL -> Production
  - Select the following characteristics different from default:
      - DB engine version 9.4.17-R1
      - DB instance class db.t2.small
      - DB instance identifier `resource-data-ckan`
      - Master username  - datastore or admin
      - Master password  - whatever you want, just save it
   - Next 
     - VPC : NRGI ECS cluster
     - Publicly accessible - yes for noew
     - Existing security group - resourcedata-posgresSQL
     - Database name - ckan
     - Disable encription
     - Enable montioring
  - Launch DB instance 
3. Let NRGI know you are doing the migration so that they do not do any dataset changes(#nrgi-resourcedata channel) 
4. Create resource-data backup
    - Go to Compose.io (credentails in LP)
    -  Click on` resource-data` 
    - `Back up now`
    - Download the new backup(it will take a while to create the backup)
5. Start postgres with the data from Compose
   - `~/PostgreSQL/pg94/bin/postgres -D <Path to unzipped backup>/data/backup/20180407125350/snapshot/conf/`
 6. Create database dump
   - `pg_dump -O -x -v -U focker --file="~/Desktop/ckan.sql" --dbname=ckan`
7. Import the database to AWS 
  -` psql -h <hostname of the instance from AWS> -p 5432 -U <username> --file="~/Desktop/ckan.sql" ckan`
8. Setup rd-beta to use new database
  - Modify task definition for rd-beta to use new database
  - Go  to AWS -> ECS-> Task definitions -> rd-beta-task -> Create new revision -> Change DATABASE_URL environment variable for rd-beta-container->Update
  - Update rd-beta service
  - check that beta.resourcedata.org works as expected and there are no errors in Papertrail.
9. After testing is complete, change https://github.com/NRGI/nrgi-dcos/blob/master/ecs/config/tasks/rd/master.json DATABASE_URL to point to the new PosgresSQL url.
10. Redeploy ckan: https://app.shippable.com/github/derilinx/ckan-docker-public/runs?branchName=nrgi
11. Test to check everything is working fine
12. Once #222 is complete, let NRGI know that the switch has been done

**Comment by grvoicu** [comment]
@adinuca Apparently pg_dump can connect to the DB via network and do the dump. We can bypass locally importing the backup. Although local space is still needed for the dump itself.

**Comment by adinuca** [comment]
@grvoicu , the problem is not the connection, is the rights you have over the database.

**Comment by adinuca** [comment]
Connection string for CKAN production: 
DATABASE_URL : postgres://ckan:WJAIFPKQDMPULXLZ@resource-data-ckan.cvu31ayb16ww.us-east-1.rds.amazonaws.com:5432/ckan

**Comment by adinuca** [comment]
Connection strings for datastore:

DATASTORE_DB_RO_URL : postgresql://datastore_ro:7lRZHkk!ZN^D31C6@resource-data-datastore.cvu31ayb16ww.us-east-1.rds.amazonaws.com:5432/datastore

DATASTORE_DB_URL : postgresql://datastore:ROVBLQCRMTHWEWZF@resource-data-datastore.cvu31ayb16ww.us-east-1.rds.amazonaws.com:5432/datastore

**Comment by adinuca** [comment]
This has been done.
