### ISSUE TITLE
When EITI files are empty do not create resources

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#23]
## Why

For the EITI dataset all countries appear to have broken download links - see for example: http://www.resourcedata.org/dataset/79258c17-7c7b-4719-8709-4e8863770e6d/resource/0b95eaf7-500f-4b1e-bb42-956980104d37/fs_download/company-payments-timor-leste.csv

**Comment by iprunache** [comment]
This is most likely because we've just switched file storage to S3 and the resource files were lost. A rerun of the EITI harvester should fix this.

**Comment by mattfullerton** [comment]
@iprunache Did the switch to S3 happen after we did the first run of the split file capable EITI harvester last week (Friday, I think)

**Comment by iprunache** [comment]
@mattfullerton yes, that's correct. We don't have the new version of the script so we weren't able to start uploading the files again ourselves.

**Comment by mattfullerton** [comment]
@iprunache 
OK, then I'll do a fresh run of the harvester from here again. I haven't sent the script yet as there is a minor problem with the first stage which is no problem if its being run manually but will be a problem for automation; I'm setting up a new staging server here and will debug it with that.

**Comment by mattfullerton** [comment]
@iprunache I'm running the script now for resourcedata.org. I've also committed the script to the public repository so you can get it set up on a schedule.

**Comment by mattfullerton** [comment]
Agreed course of action in #24 is to not create resources for empty CSVs

**Comment by mattfullerton** [comment]
2nd stage of import now checks for empty files and doesn't upload them if empty. The "don't blow away resources" part is now temporarily removed so we do a clean set of resources next-import and lose empty files. I will probably do these imports from a local machine and then we should only deploy the final one. cc. @iprunache
