### ISSUE TITLE
Investigate if the postgis_tiger_geodecoder extension error is helpful or not

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#232]
## Why
An error message related to `postgis_tiger_geodecoder` extension is logged at every deploy. This is accompanied by a message saying that `Command failed; probably not a problem`. If this is really not an issue, we should change it into a warning.

## What
- [x] It is investigated if not having postgis_tiger_geodecoder extension is a problem or not
- [x] If it isn't, a better way of handling it will be found

## Notes
When starting the application, in [70_initdb](https://github.com/derilinx/ckan-docker-public/blob/nrgi/etc/my_init.d/70_initdb) script, we drop the extension, which generates the error message. This has been happening for a while, at least since February 2018.

**Comment by adinuca** [comment]
Hi @EricSoroos, could you please take a look at this issue?

**Comment by EricSoroos** [comment]
Not important.  If it fails, the extension has (likely) already been removed.  I've pushed a change to change the message to explain better.

**Comment by adinuca** [comment]
Thank you!

**Comment by EricSoroos** [comment]
I've pushed a different change to staging that only drops the extension if it exists: https://github.com/derilinx/ckan-docker-public/commit/71f1c47de642589ff77fb1f2805f2b970c41f7e1

**Comment by adinuca** [comment]
@EricSoroos  we usually create a branch from master corresponding to an issue, merge the branch on staging to test it and merge it on master, closing the pull request, if staging works fine.

If you are confident on the changes made, you can merge to master, they will de be deployed( with shippable) immediately.

**Comment by EricSoroos** [comment]
It looks like the staging has been built and pushed, if that's successful for the changes I'll make a PR to merge to master.

**Comment by adinuca** [comment]
Hi @EricSoroos , I think this can be pushed to production. 

Thank you!

**Comment by adinuca** [comment]
This issue is no longer needed .This has been pushed to production.
