### ISSUE TITLE
Trying to grant permissions on ckan database while being connected to datastore database

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#233]
## Why
When starting the application, there are some error messages in the log regarding role and database configured for ckan not existing in the datastore databases.
## What
- [x] It is investigated why we are connecting to datastore DB and are trying to set permissions for ckan user on ckan database
- [x] Further issues are raised to fix it

## Notes
When starting the application, in [70_initdb](https://github.com/derilinx/ckan-docker-public/blob/nrgi/etc/my_init.d/70_initdb) script, we set permissions for the database, which triggers running the following script: [set_permissions.sql](https://github.com/derilinx/ckan-docker-public/blob/nrgi/ckan-home/ckanext/datastore/set_permissions.sql).

Error logs generated are:
```
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  You are now connected to database "datastore" as user "datastore".
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  REVOKE
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  REVOKE
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  ERROR:  role "ckan" does not exist
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  ERROR:  role "ckan" does not exist
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  GRANT
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  GRANT
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  ERROR:  database "ckan" does not exist
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  GRANT
Apr 20 08:48:58 resourcedata.org ecs-rd-master-task-75-rd-master-container-b2ff95b0dae1a0efa601:  GRANT

```

**Comment by adinuca** [comment]
Hi @EricSoroos , could you please take a look at this issue?

**Comment by EricSoroos** [comment]
I've pushed a change to staging that eliminates redundant database updates when we're not intentionally starting from a fresh database: https://github.com/derilinx/ckan-docker-public/commit/71f1c47de642589ff77fb1f2805f2b970c41f7e1

**Comment by adinuca** [comment]
Hi @EricSoroos , I think you can push this to production.

Thank you, 
Adina Petrean

**Comment by adinuca** [comment]
This has been pushed to production.
