### ISSUE TITLE
500 errors due to OperationalErrors

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#234]
## Why
Accessing datasets returns 500 due to Operational Errors. It happened 2 weeks ago, and it happened again today(27th April).

## What
- [ ] The cause for the Operation Error is found 
- [ ] Issue for fixing the OperationalError is raised

## Notes
The error disappears after a restart/redeploy of the application.
A Papertrail alert has been created to be able to minimize the time when the application malfunctions.

**Comment by adinuca** [comment]
Hi @EricSoroos , I think you said on Slack that you already have a fix for this. I will leave this issue opened, for tracking purposes, until the issue gets to production.

**Comment by EricSoroos** [comment]
I've pushed a change to staging that includes this: https://github.com/derilinx/ckan-docker-public/commit/ce89ef02321969cd6e37a89052908adf067dff81

**Comment by adinuca** [comment]
Hi @EricSoroos, has this been pushed to Production? 

There haven't been any errors lately and I would like to close this issue if it is no longer happening.

**Comment by adinuca** [comment]
This has been pushed to production.

**Comment by adinuca** [comment]
This happened again on the 17th of October.

**Comment by EricSoroos** [comment]
This is unlikely to be the same issue if it went away when the extension was added. The 10/17 issue appears to have been a legitimate issue connecting to the database.

**Comment by adinuca** [comment]
The application did not recover after the short while it could not connect to the database and it remained down till it was restarted in the morning.

**Comment by adinuca** [comment]
This has not happened again. Although the OperationalError was found in the logs, the application worked once the error was gone.
