### ISSUE TITLE
Saved search functionality

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#239]
Some questions/clarifications regarding the saved search functionality:

If I "Follow" a dataset by itself via its individual page (e.g: https://www.resourcedata.org/dataset/eiti-summary-data-table-for-united-kingdom), does this implement the same email functionality as the saved searches?

If I do the above, it does not show up on my "saved searches" tab for my profile: https://www.resourcedata.org/user/saved_search/. Maybe it is not expected to but I would like that. Unsure of where I can see all followed datasets at the moment.

If I "Follow" a facet search via `/dataset`, it appears in the "saved searches" tab but does not provide any meaningful information. The search below is for a single country. If I click on it it takes me to: https://www.resourcedata.org/dataset?.

![image](https://user-images.githubusercontent.com/19787025/40143187-c84701a6-5928-11e8-942d-afdbc5d36352.png)

**Comment by EricSoroos** [comment]
I've pushed some changes to staging that address this: 
* Add the query into the search querystring, fixes the search being wrong when clicking on the link: https://github.com/derilinx/ckan-docker-public/commit/e78986b87399f33368ae3d02d31311e9404eac3b
* Add better anchor text for the search link: https://github.com/derilinx/ckan-docker-public/commit/cbb2fc2bc7a2b92063f17555ee26b9e5547a7147
* Add a followed datasets tab: https://github.com/derilinx/ckan-docker-public/commit/4dc50e2e3c16480d7933fecfbc954ff0d2fac75f
