### ISSUE TITLE
Catalog.n3 and catalog.ttl return server error

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#251]
@adinuca commented on [Wed Sep 19 2018](https://github.com/NRGI/national-resource-governance-index/issues/144)

## Why
[catalog.n3](https://www.resourcedata.org/catalog.n3) and [catalog.ttl](https://www.resourcedata.org/catalog.ttl) are available on https://www.resourcedata.org/dataset and https://www.resourcedata.org/document pages.  The `n3` and `ttl` both formats return Server Error.

## What
- [ ] `ttl` and `n3` formats are removed from the page

**Comment by EricSoroos** [comment]
These are actually valid pages, and work on staging.resourcedata.org and my local staging.

**Comment by EricSoroos** [comment]
Ok, I've figured out how to fix this without major surgery.

**Comment by EricSoroos** [comment]
This fix is in production
