### ISSUE TITLE
Site header for Documents tab incorrect

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#256]
When on the "Documents" tab, the site header says "Datasets"

![image](https://user-images.githubusercontent.com/19787025/49021364-73fe4c00-f160-11e8-9f84-66a846f3ebd9.png)

**Comment by EricSoroos** [comment]
Fixed here: https://github.com/derilinx/ckanext-nrgi-published/compare/e80be361cba3214ba8d4207c16b31678e5f85eb5...51caa3f57a3d93d797465321b3d4f288d5810f20#diff-0ca56a7d626bf9dee31b70644485376c

**Comment by EricSoroos** [comment]
This fix is in production
