### ISSUE TITLE
Investigate cause of the unauthorized errors from RD

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#264]
## Why
There is an unauthorized error logged for many users of resourcedata. 

## What
- [ ] An investigation is done on where the requests care coming from
- [x] An investigation is done on how the user names have been obtained

**Comment by EricSoroos** [comment]
CKAN publishes a list of users: https://www.resourcedata.org/user

**Comment by adinuca** [comment]
Thank you @EricSoroos , I was worried that somebody hacked RD somehow as there is a request per user in the logs.
