### ISSUE TITLE
RGI source archive: Search interface 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#29]
## Why
I am wondering if you have any examples of search interfaces from other CKAN instances. The current setup looks functional - I am just wondering what options there are?

**Comment by mattfullerton** [comment]
Can we revisit this on Slack to get some more details? I'm not sure if we're talking about resource search generally or offering more search options throughout to help once RGI data is in there.

On a side note, we are developing an advanced search (where many options can be selected simultaneously so as to include or exclude metadata properties) for the Irish portal currently and can show that soon in case its relevant/inspirational here.

**Comment by mattfullerton** [comment]
Plan of action:

- [ ] Revise facets across site esp. to include important metadata fields for RGI sources
- [ ] Get all RGI data on staging site (done, but needs to be redone cf. #25 country field issue)
- [ ] Provide interlinking across metadata fields to show all other datasets with that field (i.e. question, country...)
- [ ] Possibly: "Advanced search" form - revisit once we have above items done

**Comment by mattfullerton** [comment]
See #33 for notes on facets

**Comment by mattfullerton** [comment]
See any dataset under http://li1665-139.members.linode.com/organization/rgi for a demo of hyperlinked fields

**Comment by mattfullerton** [comment]
To answer the original question, what we could consider is a more conventional "advanced search" form. Here is an example in development (only the UI, searching does not work yet):
https://li1427-232.members.linode.com/data/advanced_search (you'll have to click through the bad HTTPS warnings)

And another one from a project I did years ago:
http://open-data-map.de/

**Comment by mattfullerton** [comment]
We have hyperlinking out of datasets into listings of similar datasets. Once all the facets are done (#75), will that be enough? If so, we can close this issue.
