### ISSUE TITLE
EITI company payments CSV errors

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#30]
There are a significant amount of errors in the EITI company payment CSV ([here](http://resourcedata.org/dataset/eiti-complete-summary-table)) involving lines being carriage returned inappropriately. There are about 100 of these errors, in my estimate.

The unquoted `/` in some of the Mongolian payments appears to be one :

![image](https://cloud.githubusercontent.com/assets/19787025/25746749/d4c45f7a-3172-11e7-847b-0093b70e0822.png)

Something in this DRC payment is another:

![image](https://cloud.githubusercontent.com/assets/19787025/25746710/adeea41e-3172-11e7-9cd6-af00cf393326.png)

Many sets of Kazakhstan payments the leading 6.5 variables cut off for a particular company- see 11002 missing from 11003 to 11016; happens many times for KAZ companies:

![image](https://cloud.githubusercontent.com/assets/19787025/25746837/2ea284c2-3173-11e7-964b-044feff37081.png)

**Comment by moman822** [comment]
KAZ issue happens to Burkina Faso.

I don't see others outside of those four countries.

**Comment by anderspeders** [comment]
Can you review Matt?

**Comment by mattfullerton** [comment]
@moman822 @anderspeders This seems to always be happening in the "name_of_revenue_stream" field. The text is sometimes split across multiple lines. This is valid CSV (https://tools.ietf.org/html/rfc4180#page-3 - Section 2.6)

If its causing problems somewhere, we can tell the script to strip out new lines from texts, replacing by space or dash.

**Comment by anderspeders** [comment]
That would be great. Please proceed.

**Comment by moman822** [comment]
This needs to be changed as it prevents proper use of the data. See this screenshot of the data in Excel:
![image](https://cloud.githubusercontent.com/assets/19787025/26063177/3f31d7d0-395b-11e7-92b5-c528ef3be02d.png)

**Comment by mattfullerton** [comment]
OK, will do line-end replacement, I think the ";" character might be best

**Comment by mattfullerton** [comment]
Wasn't just revenue stream, fixed for fields where its likely to come up, please check the combined file after the next import runs

**Comment by moman822** [comment]
Still seeing some issues here. Not the same line break issue but some data inconsistencies still with data missing from columns and all other columns concatenating towards the left. 

See: Kazakhstan @ row 10189, 11759

I did not see any besides those two chunks.
