### ISSUE TITLE
Email subscribe field does not work

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#31]
## Why

![image](https://cloud.githubusercontent.com/assets/1101585/25755859/9ddc7a36-3192-11e7-92f7-b08bd722cb90.png)

**Comment by mattfullerton** [comment]
Oh dear. Looks like that was a simple design thing which does absolutely nothing. Is it meant to be there? Should it do something?

**Comment by deirdrelee** [comment]
Yep, just a UI. It could be hooked up to a mailing-list if that's a feature you would like to have?
Or maybe a contact page would be better? e.g. https://data.gov.ie/contact

**Comment by anderspeders** [comment]
Thanks. A contact form would be good. You can point to the following email alias: info@resourcegovernance.org

**Comment by mattfullerton** [comment]
This was done in https://github.com/derilinx/ckanext-nrgi-published/commit/374d4ffc7f39efc78b1073d2207b572756da39dd
