### ISSUE TITLE
RGI source archive - display of bug feed

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#32]
## Why

Some files will not display on the PDF screen viewer, for example here; 
http://li1665-139.members.linode.com/dataset/gabon-s-revised-oil---gas-regime/resource/bf89796e-e405-479b-a72c-aeb10e82bb91

Screen shot: 
![image](https://cloud.githubusercontent.com/assets/1101585/25917181/2be38986-3595-11e7-8f62-58c814d4235c.png)

**Comment by anderspeders** [comment]
http://li1665-139.members.linode.com/dataset/consolidated-financial-statements-of-rosneft-oil-company-for-the-year-ended-december---------/resource/d7eeb261-f0ca-4945-b3a6-3da3aae4bc7c

**Comment by anderspeders** [comment]
And here: 

http://li1665-139.members.linode.com/dataset/consolidated-financial-statements-of-rosneft-oil-company-for-the-year-ended-december---------/resource/d7eeb261-f0ca-4945-b3a6-3da3aae4bc7c

**Comment by mattfullerton** [comment]
And to see the real problem, we have to go to another CKAN page where flash messages are shown (I :heart: CKAN...):
"Content is too large to be proxied. Allowed file size: 1048576, Content-Length: 1276172."

I've upped the proxy limit to 70MB which should cope with most PDFs. We actually could probably get away without proxying anything, especially as we're not on HTTPS, but I'd prefer to keep that in there as its our standard config.
