### ISSUE TITLE
RGI source archive user story: Facet search by left bar

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#33]
## Why

As a User I want to to be able to browse source documents by [research question] or by [sub-component] so that I don’t have to search for each document.

(list of sub-components should have been shared already)

**Comment by mattfullerton** [comment]
Please see http://li1665-139.members.linode.com/organization/rgi for a demo of facets including question facets. The way we have the questions set up (actual data value is a number but there's also a text description) is not very CKAN-friendly, but I've overridden the default functionality to make it work.

**Comment by mattfullerton** [comment]
I think we can close this now. #75 is on the technical implementation and is outstanding.
