### ISSUE TITLE
Create staging databases for resourcedata

### ISSUE THREAD

**Issue by pax162** [NRGI/resourcedata.org#35]
## Why
At the moment the `resourcedata` application uses two databases in compose.io, `resource-data` and `resource-data-store`. The setup for the `resourcedata` dev flow will require an isolated staging environment, so we will need separate staging databases, equivalent to the production ones.

## What
- [x] Create staging databases in compose.io equivalent to the production ones, notify Frank if there are any cost increases
- [x] Copy the data from the production databases to the staging ones, we will need it for testing in #14.

**Comment by iprunache** [comment]
Created the DB and copied data. Will close once I confirm all works ok.

**Comment by iprunache** [comment]
Confirming that the staging site is functional with the staging database and has the data cloned from production.
