### ISSUE TITLE
Add IP filter security to the hosted SOLR deployment

### ISSUE THREAD

**Issue by pax162** [NRGI/resourcedata.org#36]
## Why
In #14 we switched to a hosted SOLR service. Unfortunately, the engine used by the `resourcedata` app, CKAN, does not support SOLR basic HTTP authentication. So the best we can do regarding security is to whitelist some IPs, the ones used by the virtual machines in the AWS ECS cluster.

## What
- [ ] Add the AWS ECS virtual machine IPs to the `resourcedata` deployment from searchstax.
- [ ] Test that `resourcedata` still works after adding the IPs
- [ ] Test that the solr links are no longer accessible from other IPs

**Comment by iprunache** [comment]
Added all container instances to the IP filter.

Also added the VS gateway. Add this line to your ssh config for creating a tunnel:
`LocalForward 127.0.0.1:9222 ss288577-us-east-1-aws.measuredsearch.com:443`

Then access the SOLR collection on `https:127.0.0.1:9222` and accept the security exception.
