### ISSUE TITLE
Remove company datasets where company data not available

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#42]
EITI countries w/ no company-level data still have company datasets shown in the dataset page. See [Madagascar](http://resourcedata.org/dataset/eiti-summary-data-table-for-madagascar). Can we remove these?

Other countries w/ no company data: Central African Republic, Gabon, Yemen, Nigeria, Tanzania, Timor-Leste, Ukraine.

**Comment by mattfullerton** [comment]
We already have an issue for this: #23 

We also agreed last week to prioritize RGI over EITI
