### ISSUE TITLE
PDF previews not always getting created (was: RGI document viewer Iframe issue)

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#45]
The Iframe showing pdf documents is blacked out for the bottom 1/5th. See: [here](http://li1665-139.members.linode.com/dataset/mongolian-govt-cabinet-secretariat-website79eb5/resource/502ee747-901a-42ef-8d51-4decd04a42ac). Additionally, making the iframe longer/taller overall would be preferable.

![image](https://cloud.githubusercontent.com/assets/19787025/26078872/d9f4ed06-398e-11e7-85ad-69c96f1702f2.png)

**Comment by mattfullerton** [comment]
Fixed (https://github.com/ckan/ckanext-pdfview/pull/26 will allow it to flow back into rebuilds)

**Comment by moman822** [comment]
@mattfullerton this has reappeared on staging server

see: https://staging.resourcedata.org/dataset/rgi-environmental-assessments-webpage/resource/076a72fe-50d2-4915-a9d7-318b0166abae

**Comment by mattfullerton** [comment]
This was due to our pull request (https://github.com/ckan/ckanext-pdfview/pull/26) not being merged yet. Switched the build to our version for now.

**Comment by mattfullerton** [comment]
@moman822 Could you re-create the view so we can check? (I have no CKAN account for staging)

**Comment by moman822** [comment]
I am seeing "There are no views created for this resource yet." where the iframe previously was.

**Comment by mattfullerton** [comment]
We are suffering (I think) from this:
No... seems we are suffering from https://github.com/ckan/ckan/issues/3560 - which should mean this is a non-issue for production

Brand new datasets get a preview.

This hopefully a non-issue as we have no RGI data on www.resourcedata.org. I will also adjust the import to not delete resources so this doesn't happen. But let's leave this issue open for now.

**Comment by moman822** [comment]
I'm not getting any preview on staging now.

![image](https://user-images.githubusercontent.com/19787025/27452221-d4ead2d2-575f-11e7-9fad-b53ce22b3cd8.png)

**Comment by mattfullerton** [comment]
As said, they should get created on production because we have no existing RGI datasets. If not, I'll augment the harvester to create the previews.
