### ISSUE TITLE
Landing page for RGI

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#46]
Should there be a better landing page for searching/using RGI documents? Currently there is not intro so users coming not specifically to look at RGI info would be confused by what the data is.

![image](https://cloud.githubusercontent.com/assets/19787025/26079150/b8c78016-398f-11e7-8d7f-f1c899d94a92.png)

**Comment by moman822** [comment]
![image](https://cloud.githubusercontent.com/assets/19787025/26079178/d531e778-398f-11e7-8891-9894fc9e5517.png)

**Comment by mattfullerton** [comment]
Feel free to edit the content here:
http://li1665-139.members.linode.com/organization/edit/rgi

(@moman822 has superuser access)
