### ISSUE TITLE
Organization images

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#47]
Default images for organization tabs: [here](http://li1665-139.members.linode.com/organization)

![image](https://cloud.githubusercontent.com/assets/19787025/26079210/f61e4b2a-398f-11e7-8388-b97236bfd659.png)

**Comment by mattfullerton** [comment]
There is still a lot of deletion/restoration of organisations going on. I'll see if I can include that in the scripts that orgs get created automatically with an image, but this is something you yourself can change and not a programming issue:
http://li1665-139.members.linode.com/organization/edit/rgi

(@moman822 has full superuser access)
