### ISSUE TITLE
No "description" for PNG file types

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#48]
Other file types show the "question" in this space: [here](http://li1665-139.members.linode.com/organization/f4ea5823-5c47-411d-b6de-bc3edc4b3066?res_format=PNG)

![image](https://cloud.githubusercontent.com/assets/19787025/26079441/c42974b8-3990-11e7-9058-ba798590c4c6.png)

**Comment by mattfullerton** [comment]
That's simply because the update inserting the question descriptions isn't finished yet. Coincidence.
