### ISSUE TITLE
RGI search bar not functioning

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#49]
No results under any searches other than " " (blank space): 

See:

![image](https://cloud.githubusercontent.com/assets/19787025/26079669/93af19fe-3991-11e7-88a9-4cace0cb953d.png)

**Comment by mattfullerton** [comment]
That's a bug, which I cannot easily explain. Searching for datasets works on the dataset page:
http://li1665-139.members.linode.com/dataset

And turns up datasets that are within the organization, whose's page's search in turn shows no results for the same query.

**Comment by mattfullerton** [comment]
May be related: https://github.com/ckan/ckan/issues/3291

**Comment by mattfullerton** [comment]
Notes:
...very different solr queries

solr          | 2017-05-29 13:54:09.112 INFO  (qtp575335780-18) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={facet.limit=50&q=oil+owner_org:"af7b4806-190c-4f76-b765-6891d29ccea9"&facet.field=category&facet.field=country&facet.field=assessment_type&facet.field=question&facet.field=res_format&facet.field=openness_score&fl=id+validated_data_dict&start=0&sort=score+desc,+metadata_modified+desc&fq=&fq=%2Bsite_id:"default"&fq=%2Bstate:active&facet.mincount=1&rows=21&facet=true&wt=json} hits=0 status=0 QTime=0

solr          | 2017-05-29 13:55:09.340 INFO  (qtp575335780-15) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={mm=2<-1+5<80%25&facet.field=category&facet.field=country&facet.field=assessment_type&facet.field=question&facet.field=res_format&facet.field=openness_score&fl=id+validated_data_dict&start=0&sort=score+desc,+metadata_modified+desc&fq=organization:"rgi"+%2Bdataset_type:dataset&fq=%2Bsite_id:"default"&fq=%2Bstate:active&rows=21&facet.limit=50&q=oil&tie=0.1&defType=dismax&qf=name^4+title^4+tags^2+groups^2+text&facet.mincount=1&wt=json&facet=true} hits=6365 status=0 QTime=20

**Comment by mattfullerton** [comment]
This isn't a problem on staging:
http://staging.resourcedata.org/organization/natural-resource-governance-institute?q=Peru&sort=score+desc%2C+metadata_modified+desc

**Comment by mattfullerton** [comment]
This might have had something to do with the large amount of churn on organisation creation I had when improving the import - including direct database access. It could also just be that Vitamin are using a better/more compatible Solr. Closing for now, and at some point (especially after visualizations etc. from @moman822 have been replicated on staging or production) I'll restart the derilinx dev site from scratch and hopefully this problem will disappear there also.

**Comment by derwas** [comment]
@mattfullerton how did you get this resolved?

**Comment by mattfullerton** [comment]
@derwas Sorry, I really don't know. I think it's something that might just go away with a reindex?

Other things that spring to mind is that CKAN sometimes refers to organization as owner_org, other times as organization, and sometimes with the "slug" (URL part) and sometimes with the UUID identifier. Burrowing into what SOLR queries are being used in the background (see above) might shed some light.
