### ISSUE TITLE
Generate an alert which will provide notifactions when EITI datasets are updated 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#5]
As a reviewer or user of EITI data I would like to either: 
a) have a time stamp in the metadata for whenever the latest change was done
b) create some kind of alert via email for when the data is updated

The EITI is available here: http://resourcedata.org/organization/eiti

**Comment by mattfullerton** [comment]
@anderspeders 

Last change can be found by clicking on the resource ans scrolling to the bottom, "Last updated". That data is also there for datasets, but not shown on the UI. Should we add it to the template?

The alert feature is there by clicking "Follow" on the left hand side. Maybe test it out and see if that meets the requirements.

**Comment by mattfullerton** [comment]
If @anderspeders can confirm that email alerts work for him as intended then we can close this

**Comment by anderspeders** [comment]
Let's try this as a start.
