### ISSUE TITLE
RGI change "Datasets" to "Documents"?

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#50]
## Why
I don't think "Datasets" gives an intuitive idea of what one will actually find in the RGI files.
## What
![image](https://cloud.githubusercontent.com/assets/19787025/26079898/650182da-3992-11e7-83fb-594bc8b49e17.png)

**Comment by anderspeders** [comment]
Sounds good.

**Comment by mattfullerton** [comment]
I repeat my question from #51:
Is the long term goal to have the EITI data and RGI data on one site? If so we need to remember that this is not just an RGI search but also an EITI resource search. In fact for EITI it will be even more powerful as we can search within the CSV data (Datastore). If the main goal is to keep both on one site then let's be careful about naming issues and nomenclature on the site.

... see also my comment on differentiating documents and datasets in #67

**Comment by anderspeders** [comment]
I think this question is open, but I am leaning towards keeping everything on one site for simplicity and keeping maintenance costs low. 

The argument for splitting these up would be that the RGI source library is *so* different from the standard tabular datastore that it appears confusing. 

I would be interested to hear your recommendation @mattfullerton: are you also leaning on keeping these under one roof?

**Comment by mattfullerton** [comment]
@anderspeders I know we agreed yesterday to keep them in one place and close this issue, but we could term the RGI datasets documents and the EITI ones datasets, using the type field=document for RGI and =dataset (default) for EITI imports.

**Comment by anderspeders** [comment]
I think that would work. Thanks for suggesting and please go ahead.

**Comment by mattfullerton** [comment]
Future RGI imports will file the datasets as type document leaving some work on the frontend side to display "X documents" etc.
