### ISSUE TITLE
RGI explanation of "Resource Search"

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#51]
## Why
It is difficult to understand what this feature is for, how it differs from using the search bar in the main RGI page or the sidebar filters and what are the possible queries outside of the three examples given.
## What
![image](https://cloud.githubusercontent.com/assets/19787025/26080069/ee0ace56-3992-11e7-9b64-4333b4a56501.png)

**Comment by mattfullerton** [comment]
Suggestions:

- More examples that show key parts of syntax (AND, OR, etc.), with link to Lucene query syntax (https://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#minitoc-area)
- Turn this into a general "search" page that has one bar for searching within resources, one bar for searching within datasets (copy of the bar that appears when browsing datasets), and provides scope for any other searching we want to (cf. #29, #34)

**Comment by mattfullerton** [comment]
Just a minor point that affects this and other issues (esp. #50): is the long term goal to have the EITI data and RGI data on one site? If so we need to remember that this is not just an RGI search but also an EITI resource search. In fact for EITI it will be even more powerful as we can search within the CSV data (Datastore).

**Comment by mattfullerton** [comment]
I talked to the previous developer and it seems this whole form is a legacy from an intention to file all of the PDFs under one dataset or all PDFs for one country under one dataset. Now we have for RGI datasets a 1:1 relationship dataset:resource, it is indeed fairly pointless and just confusing when compared with the normal search bar.

It could become relevant again if we have full-text searching of the resources up and running, although I suspect that that search-index info will also come up when searching datasets. I suggest unlinking the search from the UI from now. We have #29 and #34 for discussing better searching in general.

**Comment by moman822** [comment]
Agree on unlinking. I think the separate "Search" page wouldn't get much play anyway compared to the more convenient/expected search bar in the documents tab from a UI perspective.
