### ISSUE TITLE
RGI source archive: Reformatting the title field

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#54]
## Why

The current naming convention for files is not very user friendly, for example: 
BOL-2016-HY: RENDICIÓN PÚBLICA DE CUENTAS 2016 MHE

![image](https://cloud.githubusercontent.com/assets/1101585/26103470/96b3f950-3a07-11e7-9a77-c5d0d282b675.png)

**Comment by anderspeders** [comment]
Following circulation I would suggest that we try the following forma: [Document title] (assessment type, country, year) 

With this chance an example of a document title would be: 

*Economistas Mozambicanos and Natural Resource Fund (Oil and Gas, Mozambique, 2016)* 

instead of the current version: MOZ-2016-HY Economistas Mozambicanos and Natural Resource Fund

Link: http://li1665-139.members.linode.com/dataset/economistas-mocambicanos-and-natural-resource-funddc899

**Comment by mattfullerton** [comment]
Sounds good. Please mark as priority or not.

**Comment by mattfullerton** [comment]
Done in script; to be done cleanly its done with the download stage from RGI docs API, so will take a bit longer to get on to the site (clean import being done with the previously downloaded data right now)
