### ISSUE TITLE
RGI source archive: Not clear how to click the question facet on and off 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#55]
## Why

It does not appear clear to me that I can filter using the question facet. I do not see it turn on in the same way as for example the sub-component. 

![image](https://cloud.githubusercontent.com/assets/1101585/26103700/b7d2d2ae-3a08-11e7-8266-a81c5e7de9ce.png)

**Comment by mattfullerton** [comment]
Yes, they aren't real facets (the real facets are the numbers, not the titles), so this isn't possible.

The technical background: https://github.com/derilinx/ckanext-nrgi-published/commit/ef9b49646f925fae9f76cc1adca2c079966df21b

The "fix" is to store the full question text in the dataset - that has advantages and disadvantages: advantage is that it would make faceted search easier (although I have not yet been able to get CKAN to properly process the multiple questions as single facets, as it does for example with file formats). Disadvantage is that lots of searching against a long text string is happening in the background and changing the slightest thing in the question text is then a little problematic. I don't know how conscious a decision it was earlier to base things around question numbers and not texts.

**Comment by mattfullerton** [comment]
All of that said; it might well be possible to manually display it as "on" when the search that has happened based on facet-clicking appears. I can look into that. Its just all a bit messy, but CKAN provides no good way for associating labels with values except in a couple of places thanks to the scheming extension we use.

**Comment by anderspeders** [comment]
Ok, thanks. I'd like to trust that we test this course of action and we will be quick to review.

**Comment by anderspeders** [comment]
It would be great to have something to show on Monday, though I am aware that this is short notice.

**Comment by mattfullerton** [comment]
In the end this wasn't too hard to build in; working now.

**Comment by anderspeders** [comment]
This is an amazing addition. Thanks a lot @mattfullerton
