### ISSUE TITLE
Confirm dataset count

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#56]
## Why
[Not urgent]

I am seeing various numbers. Currently we are ticking 16k documents and so I am wondering about duplicates...?

**Comment by mattfullerton** [comment]
Bear with me - I want to get a clean import and will then clear out the DB and do a full (working) import. Right now there are duplicates from successive imports; documented this in #52

**Comment by mattfullerton** [comment]
All datasets have been deleted and a clean import is running. Now that we have the names issue (#52) more or less solved future imports will update instead of creating new datasets.
