### ISSUE TITLE
Correction in metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#57]
## Why

Please correct to: 

Version: 2017 Resource Governance Index
Maintainer: Natural Resource Governance Institute
Email: Natural Resource Governance Institute

![image](https://cloud.githubusercontent.com/assets/1101585/26104689/fffc69d8-3a0c-11e7-9502-9fcaf83efe2e.png)

**Comment by mattfullerton** [comment]
Will do

**Comment by mattfullerton** [comment]
Done; importing with these values as we speak
