### ISSUE TITLE
Server error when CKAN search is initiated

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#6]
![image](https://cloud.githubusercontent.com/assets/1101585/25013438/85c2ad2e-2041-11e7-836a-a6b5a4d2679d.png)

When I search  I get a server error: http://resourcedata.org/resource_search

**Comment by iprunache** [comment]
Not sure how the search is supposed to work. At first sight it looks like a structured query that only accepts searching for resource fields know to CKAN. Any other query fails.

@mattfullerton could you help with this?

**Comment by mattfullerton** [comment]
Yes. And internally it throws a helpful error message:  {'query': u'Must be <field>:<value> pair(s)'}, but we need to catch this and display it. The instructions for structuring the query (albeit a little terse) are there with the search.

This is something we could do, cc. @deirdrelee

**Comment by mattfullerton** [comment]
I will improve the error message that comes back when the query isn't formatted right and hopefully we will improve searching in general, cf. #29

**Comment by mattfullerton** [comment]
see #51; we possibly should stop development on this feature
