### ISSUE TITLE
Is language a possible metadata/filterable field?

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#60]
For RGI source documents. This would be a helpful addition.

**Comment by anderspeders** [comment]
This is also a broader question regarding the types of metadata that might be available for source documents and if anything is currently not included.

**Comment by mattfullerton** [comment]
In general anything stored in the metadata ("additional info") of the dataset is easy to add to the filters. If its additional info of the files/resources/PDFs, it it a bit more complicated but also possible.

**Comment by anderspeders** [comment]
I checked and language does not seem to appear. Closing this.
