### ISSUE TITLE
Removing "Openness" score

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#62]
## Why
This is meaningless without further explanation (which I couldn't find) and just makes it look like all the available data is sub-par (since they are all one star).
## What
![image](https://cloud.githubusercontent.com/assets/19787025/26123744/fbdb82a2-3a49-11e7-8adc-5adeee17762f.png)

**Comment by mattfullerton** [comment]
I agree this probably doesn't make much sense for RGI. What about EITI? Its something we put in as standard on our CKANs but we can take it out.

**Comment by moman822** [comment]
I think for anyone using the site, that the data is available on the site will mean it is sufficiently open. So I would suggest removing completely. @anderspeders?

**Comment by anderspeders** [comment]
I suggest we remove from RGI, but not from other parts of resourcedata. 

For now I will not flag this as priority.

@moman822 we want to keep the destinction for the parts of resourcedata that hosts a diversity of spreadhseet types.

**Comment by mattfullerton** [comment]
For now I've removed it completely (my anticipation is that this will only be shown on Derilinx staging, not on resourcedata.org, as I don't think we're ready to base that off GitHub just yet). We can make the on/off distinction more nuanced after Monday/after launch. Reopening issue as I see this isn't the final fix.

**Comment by anderspeders** [comment]
Thanks. Sounds good.

**Comment by iprunache** [comment]
@mattfullerton what would you say it's missing on `resourcedata.org` to get it working there? I'd like to get `resourcedata.org` on par with Derilinx's staging env sooner rather than later. If the code is not production ready yet we could run it on NRGI's staging instead.

**Comment by mattfullerton** [comment]
I've already pushed the latest code to "staging" instead of "nrgi" to move this forward

**Comment by moman822** [comment]
This looks taken care of on the RGI documents but still remains in the sidebar. If that is OK then can we close?

**Comment by mattfullerton** [comment]
We shouldn't close because right now its completely disabled and we want it back on for EITI Datasets. The facet thing is a good point, I will see if I can get that facet turned off when there are no facets to show (which will be the case once we do an import with the extension tuned not to process documents).

**Comment by mattfullerton** [comment]
Done.

Example of it being on and off for data and documents respectively should be here shortly:
https://staging.resourcedata.org/dataset?_country_limit=0&country=Ukraine&_show_all_types=True
