### ISSUE TITLE
Front page: remove image links

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#63]
## Why
The various category links don't connect to any datasets. Unless they are going to be linked, they should be removed.
## What
![image](https://cloud.githubusercontent.com/assets/19787025/26123901/9bf4f6ba-3a4a-11e7-88d7-2c17ffda83c4.png)

**Comment by mattfullerton** [comment]
But on resourcedata.org (i.e. EITI datasets) they do...

**Comment by moman822** [comment]
@anderspeders worth keeping? Right now the datasets only use a couple of these tags ("category" in the dataset metadata). I think we discussed this before briefly.

I lean towards removing them or removing the unlinked ones, if possible (probably has issues with when new categories are added).

**Comment by moman822** [comment]
Let's keep these, as the RGI documents are now linked. Closing.
