### ISSUE TITLE
Change front page title

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#64]
I suggest "ResourceData".

![image](https://cloud.githubusercontent.com/assets/19787025/26123991/e7a9d882-3a4a-11e7-99de-af9c977623d9.png)

**Comment by anderspeders** [comment]
Agree.

**Comment by anderspeders** [comment]
I will need to check first. Please sit tight.

**Comment by moman822** [comment]
@anderspeders Any update on this?

**Comment by moman822** [comment]
@anderspeders is "Resource Data" or "ResourceData" good here?

**Comment by mattfullerton** [comment]
Did you decide to leave it as "Open Data"? Can we close this?

**Comment by deirdrelee** [comment]
Change to 'Resource Data' and close issue :)

**Comment by moman822** [comment]
Looks great. Closing.
