### ISSUE TITLE
Finding added "Pages" when not logged in

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#65]
## What
Navigating to account-created "Pages" via the "Pages" tab is only possible for users who aren't logged in via a URL (see: http://li1665-139.members.linode.com/pages/wvarv). There is no button or link on the web page to direct a user to content created this way.

Can we create either a tab along this top toolbar
![image](https://cloud.githubusercontent.com/assets/19787025/26124410/4fe248a2-3a4c-11e7-9f52-0f9a6472d4c3.png)

or are there other options?

**Comment by mattfullerton** [comment]
Tab on top bar is easy. I guess the idea should maybe be to make pages inter-navigable, then perhaps only link to one page from that menu - thus creating a kind of CMS/Wiki, which is the idea of ckanext-pages.

**Comment by moman822** [comment]
That sounds really good.

**Comment by mattfullerton** [comment]
I'll make the tab just for now to the listing of all pages, but in the medium term you  (@moman822) can create a "gateway" page for the pages content?

**Comment by moman822** [comment]
Can I?

**Comment by mattfullerton** [comment]
What I mean is make one page that serves as an entrypoint/overview and use links on that page to get to other content you want to promote; rather than a generic CKAN pages listing this would be better for users, I think?

**Comment by moman822** [comment]
Ok, that makes sense. Good idea.
