### ISSUE TITLE
Spell out question in left bar (instead of current truncation)

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#66]
## Why

Many of the questions in the RGI are lengthy and thus it makes it difficult for users to navigate these when they are presented truncated. Would it be possible to ppell out the content of question in left side bar: 

![image](https://cloud.githubusercontent.com/assets/1101585/26124613/1bc6231c-3a4d-11e7-92fb-81561e637434.png)

**Comment by mattfullerton** [comment]
Absolutely possible, obviously just be aware that this will dramatically length the physical length of that list. This probably relates to other issues where I feel like we are considering whether faceted search is the best way to do this navigation. I'll do it and we can see how it looks.

**Comment by anderspeders** [comment]
Thanks, that would be great.

**Comment by mattfullerton** [comment]
Demoing now at http://li1665-139.members.linode.com/dataset - let me know what you think.

Worth noting: the full question always appeared as a mouseover text

**Comment by mattfullerton** [comment]
Any feedback on this?

**Comment by anderspeders** [comment]
Thanks Matt. Looks really good. 

We may receive more feedback later but I suggest that we close for now
