### ISSUE TITLE
Change metadata tabs on front page

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#67]
#### Sources
2 sources is misleading. The RGI documents come from thousands of sources. Having "2,342 Sources" would not be anymore useful though.

#### Datasets
Showing 6,000 datasets is misleading because as I flagged in #50 they are not "datasets" as most would consider. Also, it just doesn't tell a user much about the site.

#### Countries
This is OK

## What
Unsure what fields would best replace "Sources" and "Datasets". Perhaps "Years" as in years covered (substantial number including EITI data but also misleading) could be one?

Additionally, these seem like they would be links but are not. Should be added as such if they are ultimately kept and there is a relevant location to link to.

![image](https://cloud.githubusercontent.com/assets/19787025/26125072/cdf827c8-3a4e-11e7-833b-b7490c42b789.png)

**Comment by moman822** [comment]
Thoughts @anderspeders? Similar to our discussion on RP front page.

**Comment by mattfullerton** [comment]
I would propose listing #documents and #datasets separately, where datasets is all datasets with tabular data attached (i.e. PDFs excluded) and documents are the PDFs.

There are more elegant ways to do this as its a common problem facing open data/transparency portals: how do we describe open information that isn't really a dataset (think council meeting minutes, planning permission documents, etc.)

cf. #50

**Comment by moman822** [comment]
"Datasets" & "Documents" makes sense to me. I think go for it.

**Comment by anderspeders** [comment]
Please go ahead Matt

**Comment by mattfullerton** [comment]
Please note we will see documents > 0 once we do a fresh import; waiting for feedback on #78
