### ISSUE TITLE
Trigger resourcedata.org deploy when changes are pushed to nrgi extensions

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#68]
## Why
Development for the CKAN instance behind resourcedata.org is done on 3 repos and we want to trigger a deploy whenever changes are pushed to one of those repos.

While `derilinx/ckan-docker-public` will be used to build the container image for deployment, the other two repos containing extensions for CKAN should also trigger a build and deploy of the container image.

## What
- [x] a Shippable build of the `derilinx/ckan-docker-public` repo is triggered when changes are pushed to the `derilinx/ckanext-nrgi-published` repo
~~- [ ] a Shippable build of the `derilinx/ckan-docker-public` repo is triggered when changes are pushed to the `derilinx/ckanext-dietstars` repo~~

## Notes
We will first build this pipeline first for the `rd-staging-service` by using `staging` branches. Once the entire pipeline is set up we will replicate this for the production service and master branches.

**Comment by mattfullerton** [comment]
@iprunache in #62 we are discussing removing dietstars. Apart from that, this is an extension that can basically be seen as third party (in fact, I should switch to grabbing it from GitHub instead of as a submodule). So regardless of #62 I would drop it as a trigger.

**Comment by iprunache** [comment]
Thanks for the info, Matt, we'll drop it.


[image: Vitamin Software Logo]

*Ionut Prunache*
ionut@vitaminsoftware.com
Software Engineer
vitaminsoftware.com <http://www.vitaminsoftware.com/>

**Comment by iprunache** [comment]
Done in derilinx/ckanext-nrgi-published#1
