### ISSUE TITLE
Build pipeline is replicated for the production service

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#71]
## Why
After implementing the build pipeline and confirming it works on a staging environment we need to replicate it to the production environment so that developers can start using it to deploy to production.

## What
- [ ] deploy pipeline for `resourcedata.org` staging service is replicated for the `rd-master` service using the master branches of the code repos

**Comment by iprunache** [comment]
Had to update the solr schema being used by the master and staging collections. The newest CKAN code is using schema version `2.7` versus `2.3` which was previously configured.

**Comment by iprunache** [comment]
Created Postgis extension for the databases:
postgis:

psql -U admin -h aws-us-east-1-portal.18.dblayer.com -p 15596 -d ckan-staging
psql -d yourdatabase -c "CREATE EXTENSION postgis;"
psql -d yourdatabase -c "CREATE EXTENSION postgis_topology;"

psql -U admin -h aws-us-east-1-portal.18.dblayer.com -p 15596 -d ckan
psql -d yourdatabase -c "CREATE EXTENSION postgis;"

**Comment by iprunache** [comment]
We'll enable the production pipeline once we get the code running on staging without error.

**Comment by anderspeders** [comment]
Can you provide a status here?

**Comment by iprunache** [comment]
The latest code is still not running without error on staging.resourcedata.org.

@mattfullerton is working on a fix and when everything works on staging we'll replicate the pipeline to production too. I estimate we'll need a couple of days to replicate so if Matt gets the fix in today we'll have this ready this week.

**Comment by iprunache** [comment]
Done. Code pushed to derilinx/ckan-docker-public on the `nrgi` branch will be automatically deployed to production.
