### ISSUE TITLE
Setup datastore for resourcedata.org

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#74]
## Why
Allow resourcedata.org to use complex visualisations plugins that require the datastore plugin to be installed.

## What
~~- [ ] datapusher docker image is built and pushed to DockerHub~~
- [x] datapusher container is added to the rd-master and rd-staging task definitions and linked to the ckan container
- [x] `.csv` and `.xls` resources are pushed to the CKAN datastore as soon as they are uploaded

## Notes

https://github.com/ckan/datapusher

DockerHub repo with recent datapusher builds: https://hub.docker.com/r/easyckan/ckan-datapusher/~/dockerfile/

**Comment by anderspeders** [comment]
Thanks. What is the timeline for this?

**Comment by iprunache** [comment]
@anderspeders we can get this done by Wednesday the 24th.

**Comment by anderspeders** [comment]
Thanks!

**Comment by iprunache** [comment]
Used a datapusher image from DockerHub to make the datastore integration work.

Verified that it works on staging.resourcedata.org. Manually uploaded this resource to the datastore:
http://staging.resourcedata.org/dataset/eiti-summary-data-table-for-ukraine/resource/ecebbf84-8717-46a5-9ca1-1c30e8d0fc59
