### ISSUE TITLE
Investigate if CKAN properly cleans up unused resources from the S3 storage

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#77]
## Why
The import-heavy nature of the site means that new or existing resources are repeatedly imported and if CKAN does not do a proper job of cleaning up unused/replaced resources then S3 storage usage can swell over time leading to unnecessary costs.

## What
- [ ] check if CKAN duplicate resources when they are reimported
- [ ] check if CKAN cleans up unused resources

## Notes
Quote from @mattfullerton:
```
At some point it may be worth doing a few tests to see how good CKAN is at cleaning up deleted resources. We sometimes have a lot of turnover of resources due to the import-heavy nature of the site.
```

**Comment by moman822** [comment]
@iprunache is this process coming along and how much of a priority is it for launch? Thanks.

**Comment by iprunache** [comment]
@moman822 this should be low priority for the launch as its purpose is to potentially reduce storage costs for the resources being uploaded to CKAN. We haven't started work on it yet.

**Comment by adinuca** [comment]
This hasn't been an issue so far. Closing it.
