### ISSUE TITLE
Revised metadata

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#78]
We have received a final framework from the RGI team with the final names for the componenets and sub-components, which should be updated accordingly. I have the names in an Excel file, let me know where to upload/send that and I will do so.

Tasks:
- [x] Address missing questions
- [x] Script to process data into components and question list
- [x] Script outputs revised data for schema (questions.json in repo)
- [x] Schema updated
- [x] Rerun import and check for errors/that new metadata matches RGI API output

**Comment by mattfullerton** [comment]
I have the new Excel file, thanks.

There are missing questions; I assume this is in general fine. I notice though for example that Q1:
1. How does the country legally define the ownership of subsoil extractive resources?

Currently has a large number of PDFs associated with it in the DB:
http://li1665-139.members.linode.com/dataset?_question_limit=0&question=%5B%5C%22001%5C%22%5D

Do you think these PDFs will now be filed under a new question in the RGI API? I'm reluctant to re-run the import without knowing. I have processed the Excel data now though and have it ready to go, which will change the sub-component names as requested in #78. However, we currently only store sub-components (formerly categories) in the DB. Do you want to add component as well? Indicator is also not used. Law/Practice I have on my radar (#79)

**Comment by moman822** [comment]
I will follow up on the missing questions.

Re components/indicators: I think leave those out. I think there are too few "Components" and too many "Indicators" to be useful. The six or so "Sub-components" seems like the sweet spot for filtering. Proceed with Law/practice when you can.

**Comment by moman822** [comment]
I have received a response on this question. Short answer: please remove documents tagged with the following questions from the databank:

27
30
31
57
58
74
76
81
83
103
104
108
123
131
137
139
140
141
152
153

Leave all others in there. Does that work?

**Comment by moman822** [comment]
Long answer (from RGI researcher):

- I shared the framework for the calculation of the RGI, which uses a subset of the information collected in the data collection process.
- There are context questions included in the original questionnaire, such as question 001 below, which sets the scene for the forthcoming questions but cannot be generated into a score on a scale of 0 to 100.
o   These questions will be published alongside the questions that have scores assigned to the responses.
o   These questions should feature in the databank – as you mention, there are a wealth of documents tagged to these questions.

- Following various runs of the index, it became evident that some of the questions (20 in total) were poorly worded and not generating comparable results across the sample.
o   These questions will not be published.
o   These questions (below, and attached) should be removed from the databank.

...
(list of questions)

**Comment by mattfullerton** [comment]
What should I do with questions that have those questions but also another question which _isn't_ missing? Leave them there? References to missing questions are already removed automatically.

I would suggest:
for each PDF:
    for each question of PDF.questions:
        if question not in list:
            remove question from PDF.questions
    if length(PDF.questions) == 0
        don't upload (or indeed, delete if already existing)

Looking and thinking about the longer answer, I think this is correct - the researchers start with the questions and answer these and reference PDFs. We want to keep the PDFs for good questions and drop them for bad ones. Whether a PDF is relevant for multiple questions is not really relevant.

**Comment by moman822** [comment]
Yes, that is correct.

So, if PDF_1 is tagged with the questions:

- Q001 (_not_ in remove list & _not_ in new framework list)
- Q002 (in new framework list [the Excel file])
- Q027 (in remove list)

After processing it should be tagged with Q001 and Q002.

**Comment by mattfullerton** [comment]
Ah! Then its even more complicated? The remove list is _not_ the same as the missing questions from the Excel? Is it not possible to send an Excel with a complete list of up to date questions?

**Comment by mattfullerton** [comment]
It sounds dangerous not to have a single list of questions to work from, and more work to combine them into a single list (I need this for CKAN). But I can do it.

**Comment by moman822** [comment]
Let me ask for a full list of questions.
