### ISSUE TITLE
Add law/practice filter

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#79]
The final framework file mentioned in #78 also contains a column designating each question as either "Law" or "Practice", regarding the question content. Can we add this to the filter sidebar as well?

**Comment by mattfullerton** [comment]
This can be done, but raises some of the same problems I'm facing in #75 - we will have to store this against the dataset and not against the question, and as documents can have multiple questions, then they will have to have the capability to store both of these fields as well. Once I get #75 done I can tackle this.

**Comment by anderspeders** [comment]
Thanks Matt.

**Comment by anderspeders** [comment]
@mattfullerton Are there any updates here?

**Comment by mattfullerton** [comment]
Just wanted to point out that this priority but not launch (we don't have a sep. label for that and I don't think its worth creating one at this point)

**Comment by mattfullerton** [comment]
This is tied into #75

**Comment by anderspeders** [comment]
I think we concluded with a sufficient solution to this before launch. Closing here.
