### ISSUE TITLE
Folder redirect redirects from `https` to `http`

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#82]
## Why
Users should not be directed to the insecure version of the site when accessing urls that end with a `/` so that they continue to benefit from a secure connection.

## What
- [ ] folder redirects no longer redirect from `https` to `http`

## Notes
`https://staging.resourcedata.org/dataset/` redirects to `http://staging.resourcedata.org/dataset`
Notice the change of protocol from `https` to `http` ^^

**Comment by moman822** [comment]
@iprunache is this process coming along and how much of a priority is it for launch? Thanks.

**Comment by iprunache** [comment]
@moman822 we didn't start working on this yet but I think we should get it ready for launch so that users can only use the secure version of the site.

Is there a target date for the launch?

**Comment by iprunache** [comment]
derilinx/ckan-docker-public#4 fixes this somewhat but it requires 2 301 redirects. I think that's satisfactory as the users can't get to an url ending in a `/` by browsing the urls on the site but by only typing it manually which should be very rare.
