### ISSUE TITLE
double scrollers

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#84]
## Why

Can we do something about the double scrollers appearing in the viewer - for example here: https://www.resourcedata.org/dataset/eiti-complete-summary-table/resource/3b01a422-8703-46c1-919b-507feeb161a2

![image](https://user-images.githubusercontent.com/1101585/26891462-1360c7e4-4b83-11e7-962f-e8d17fee7449.png)

**Comment by mattfullerton** [comment]
@anderspeders Do you still see this? Which browser? Was the window very small? I don't see this.

**Comment by moman822** [comment]
I also get this on only the Complete Summary Table

see: https://staging.resourcedata.org/dataset/eiti-complete-summary-table/resource/969e98b7-c093-4bc0-aff7-80b4255ef1f0

**Comment by mattfullerton** [comment]
Yes, it is some interplay of window size and the preview being inside an iframe. Basically a CKAN problem that could be tricky to fix. Is the graphing function useful on these individual datasets? We could move to a simpler/less messy previewer.

**Comment by moman822** [comment]
Graph function is not necessary.

**Comment by anderspeders** [comment]
Depending on how much other stuff is happening this is not a top priority.

**Comment by mattfullerton** [comment]
I've replaced recline grid view with the new datatables view. This view doesn't have the double-scrollers problem. This is how new imports will look:
http://li1665-139.members.linode.com/dataset/test-auto-datatables/resource/e4b3d442-d9e1-43df-ab48-fe8cefb2c571

This should take effect after the next automatic run of the EITI harvester, as we are still recreating resources on every run (#88).
