### ISSUE TITLE
Automatically rebuild Docker images for harvesters when new code is pushed

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#85]
## Why
Create a continuous deploy pipeline for harvesters so that the latest code updates are used in production as soon as they are available without requiring human interaction.

This allows developers to deploy their improvements to production immediately by just committing their working code.

## What
- [ ] the eiti harvester Docker image is rebuild when new code is pushed to the master NRGI/resourcedata.org master branch
   - [ ] the image is tagged as `nrgi/resourcedata.org-harvesters:eiti.master.<SHA>` using the latest commit SHA and pushed to DockerHub
   - [ ] the image is also tagged as `nrgi/resourcedata.org-harvesters:eiti.master` and pushed to DockerHub as the latest available version
- [ ] same process is implemented for the staging branch

**Comment by moman822** [comment]
@iprunache is this process coming along and how much of a priority is it for launch? Thanks.

**Comment by iprunache** [comment]
@moman822 this would not impede the launch as we can do this manually now. But it's something I would like to finish right after addressing the priority issues so that we have a fully automated deploy pipeline not just for the site but the for the data import scripts too.

**Comment by iprunache** [comment]
This was done in #195 .
