### ISSUE TITLE
Persist datapusher jobs to an external DB

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcedata.org#87]
## Why
Prevent CKAN from complaining that it cannot connect to the datapusher after a datapusher container restart when managing the datastore for resources that have been already uploaded to the datastore.

Since datapusher now stores it's jobs logs to a local store on the container the logs get lost when the datapusher container gets restarted and they are no longer available to be displayed in the CKAN resource management tab.

## What
- [ ] datapusher jobs are persisted to an external DB

## Notes
The DB seems to be configured through this variable in the datapusher settings file: `SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/job_store.db'`.

We could create a database inside the PostgreSQL datastore deployment for the datapusher alongside the datastore db.

**Comment by adinuca** [comment]
This hasn't  been a problem so far. Closing.
