### ISSUE TITLE
Only replace dataset resources if they actually changed

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/resourcedata.org#88]
This may be tricky and the easiest (albeit slow) thing might be to do a diff of the current resource and the fresh one, and only then update it. However, an improvement would already be to UPDATE the resource instead of what we do now which is update the dataset with 0 resources and then (re)upload the resources, which results in new URLs for the resources. The actual resources created incorporate all years etc. and are always named the same, so really an update is far more appropriate here than a replace.

**Comment by mattfullerton** [comment]
cf. #83 - if my suggestion there is to work properly we need to a) Check that users get emailed when a resource_update happens and b) Not annoy them with dummy updates

**Comment by anderspeders** [comment]
Not valid for RGI source library I think

**Comment by mattfullerton** [comment]
Unfortunately it is valid; the scripts work by updating the dataset/clearing the resource and then uploading the resource. But making the change for RGI should be easier, its probably fine to just compare PDF URLs.

**Comment by mattfullerton** [comment]
Correction: The update in the RGI import is all-at-once including the resource. Whether CKAN is smart enough to realise the resource is the same I'm not sure. Will check.

**Comment by anderspeders** [comment]
I wonder, I if we can simply add the time stamps to the EITI datasets (https://github.com/NRGI/resourcedata.org/issues/127) we should be able to close this issue.

**Comment by anderspeders** [comment]
Tentatively closing here due to above reason.

**Comment by mattfullerton** [comment]
@anderspeders Actually you're almost right about irrelevance for RGI; because we do not regularly update the RGI library, and if we do its probably because we want to change something (so, de facto update), I don't think we need to do this for RGI import. The above commit is for EITI import which I believe is running weekly.

**Comment by mattfullerton** [comment]
Going to test the whole EITI import on staging now
