### ISSUE TITLE
Make file download more obvious from "Explore" tab

### ISSUE THREAD

**Issue by moman822** [NRGI/resourcedata.org#89]
It is not intuitive that the "URL" link at the top of the panel triggers the file download. Can we change this to a button?

![image](https://user-images.githubusercontent.com/19787025/27043380-f530fbac-4f67-11e7-82a4-0bf16b64b9e7.png)

**Comment by mattfullerton** [comment]
The button is there, "Go to Resource", above the link. I find links a more intuitive way to know I'm being redirected to another page or file. But maybe that's just me. Or am I missing something?

**Comment by moman822** [comment]
Ok, I did not understand what the "'Go to resource" button did. Can we change "Go to resource" to the more obvious "Download" and close? Also make the same change on the dropdown "Explore" tabs on these pages: https://www.resourcedata.org/dataset/peru-extractive-industry-contextual-data1

**Comment by mattfullerton** [comment]
That's possible. The reason for the ambiguity is that links can be anything (i.e. a 3rd party site or API and not a file). But in NRGI's case it will always be a file.
