### ISSUE TITLE
Always redirect to www.

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/resourcedata.org#9]
The server URL is set to www.resourcedata.org but resourcedata.org works too. This is a problem for Javascript calls which are embedded in the page and talk to www. As this is a different domain we then have CORS issues.

I.e. the "follow" button generates this when I am on http://resourcedata.org:
`XMLHttpRequest cannot load http://www.resourcedata.org/api/action/follow_dataset. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

Rather than trying to fix that I would suggest just always redirecting to www.

**Comment by iprunache** [comment]
Tracked on #16
