### ISSUE TITLE
Please rename Users club to Receive updates from NRGI

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#92]
## Why

Please rename to: Receive updates from NRGI

Text: Sign up to receive updates from NRGI. 

Link to: http://resourcegovernance.us2.list-manage1.com/subscribe?u=586ab656ca1263b8776b1f081&id=81af06e868

![image](https://user-images.githubusercontent.com/1101585/27057368-e8306582-4f99-11e7-80c1-678cb61c7429.png)

**Comment by anderspeders** [comment]
Similarly add link to this field: 

![image](https://user-images.githubusercontent.com/1101585/27079610-4d9a9610-5006-11e7-99b8-315781a1d847.png)

**Comment by iprunache** [comment]
@mattfullerton could you have a look at this?

**Comment by mattfullerton** [comment]
N.B. I dropped the "Us" from "Join Us" as it didn't sit so well. Perhaps we should even switch to "Sign up" or "Subscribe"
