### ISSUE TITLE
Rename updates / users club section

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#93]
## Why

Please rename to: Receive updates from NRGI

![image](https://user-images.githubusercontent.com/1101585/27057368-e8306582-4f99-11e7-80c1-678cb61c7429.png)

**Comment by moman822** [comment]
This is the same as above image on staging server; was it ever changed?
@mattfullerton 

https://staging.resourcedata.org/

**Comment by mattfullerton** [comment]
@moman822 It was never changed because Anders closed the issue - @anders?

**Comment by mattfullerton** [comment]
Ah we have two issues for the same thing (#92)...
