### ISSUE TITLE
Publish Analysis Content

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#94]
## Why

This section does not make much sense at this stage: 
![image](https://user-images.githubusercontent.com/1101585/27057662-0e419a06-4f9b-11e7-9f5f-50832cd75702.png)

**Comment by mattfullerton** [comment]
@moman822 Would you like to copy over your work from Derilinx-staging to the live site?

**Comment by anderspeders** [comment]
@moman822 If we are ready with this - let's bring it over.

**Comment by moman822** [comment]
Not ready. I will spend this week finalizing that.
