### ISSUE TITLE
Deploy RGI source library to ResourceData from staging server

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#97]

**Comment by anderspeders** [comment]
Can we close this now?

**Comment by iprunache** [comment]
Isn't the goal here to get the data on `www.resourcedata.org`? We only have it on `staging.resourcedata.org`.

**Comment by mattfullerton** [comment]
er, yes, I got mislead by Ander's deleted comment who maybe misinterpreted it the same way I did. sorry.

**Comment by anderspeders** [comment]
Please deploy tomorrow, Tuesday AM.
