### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#98]
## Why

Not sure if this has already been implemented. If yes, please close. 

If no, Frank will have the details. Please reach out on email.

**Comment by iprunache** [comment]
@mattfullerton we're exporting the GA code to the `GA_CODE` env variable. Could you make sure that is used by the GA script in CKAN?

**Comment by mattfullerton** [comment]
You should be getting GA calls from staging now, can you check?

P.S. This may put us in breach of EU cookie guidelines

**Comment by mattfullerton** [comment]
Please note the extension wants google log in details and the name of the GA section, but I believe this is all to do with monitoring GA from _within_ CKAN. It seems to have started up without those details and unless anyone wants to use the facilities in CKAN I would say we steer clear of that part.

See:
https://github.com/ckan/ckanext-googleanalytics#installation
and https://github.com/ckan/ckanext-googleanalytics#authorization

**Comment by mattfullerton** [comment]
@iprunache Did you get any feedback about whether this is working?

**Comment by iprunache** [comment]
@mattfullerton not yet but I just sent an email to Frank to get a confirmation that it's working. Will close when I'll get that(Frank is out of office until the 11th).

**Comment by iprunache** [comment]
We got confirmation that we are tracking the site:

<img width="771" alt="ua-16486048-5" src="https://user-images.githubusercontent.com/15313824/27799016-3d52d0da-601c-11e7-9758-e3aa558dbc87.png">
