### ISSUE TITLE
Change header and text for TODAY section

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcedata.org#99]
## Why

Change header: Explore data from Extractive Industry Transparency Initiative (EITI, 

Text: NRGI is providing EITI Summary data including company payment information in a user friendly format country by country. 

LinK: http://www.resourcedata.org/organization/eiti

![image](https://user-images.githubusercontent.com/1101585/27080048-36a46aec-5008-11e7-8bd2-6f0d882dc16e.png)

**Comment by moman822** [comment]
Let's leave the text and point this to the "Analysis" page (which I am finalizing)

**Comment by moman822** [comment]
changing in favor of #113
